percy/cli

- lerna.json
- packages/cli-build/package.json
- packages/cli-command/package.json
- packages/cli-config/package.json
- packages/cli-exec/package.json
- packages/cli-snapshot/package.json
- packages/cli-upload/package.json
- packages/cli/package.json
- packages/client/package.json
- packages/config/package.json
- packages/core/package.json
- packages/core/src/server.js
- packages/dom/package.json
- packages/env/package.json
- packages/logger/package.json
- packages/sdk-utils/LICENSE
- packages/sdk-utils/README.md
- packages/sdk-utils/index.js
- packages/sdk-utils/package.json
- packages/sdk-utils/test/.eslintrc
- packages/sdk-utils/test/helper.js
- packages/sdk-utils/test/index.test.js
Node based SDKs have a few common utils that can be abstracted away into their own module. They also perform common setup steps in tests that can also be abstracted away into a common test helper. 
These common utils include talking to the local running Percy CLI API. Rather than have dependencies on libraries like fetch, we can use a shared request helper using native Node methods. Also, rather than including all of the `winston` dependencies of `@percy/logger`, there is a smaller, simple log util that accomplishes the goal of communicating SDK information to the user. 
The consumable utils exported by this package are `log`, `getInfo`, `isPercyEnabled`, `fetchPercyDOM`, and `postSnapshot`. [Their usage docs can be found in the readme](https://github.com/percy/cli/blob/1eedb03c72cedd2263e …
> ✨ @percy/sdk-utils

- packages/cli-config/package.json
- packages/cli-config/src/hooks/init.js
- packages/cli-config/test/validate.test.js
- packages/config/package.json
- packages/config/src/defaults.js
- packages/config/src/load.js
- packages/config/src/normalize.js
- packages/config/src/validate.js
- packages/config/test/index.test.js
- yarn.lock
Some aspects of config merging was broken due to either frozen objects, or strange rules around empty objects.
Additionally, the `config:validate` command did not validate core configuration options because the schema is not yet loaded when that command is run.
Remove the deepmerge dependency which seemingly will override objects when merging an empty object. This functionality was easy to replace by utilizing the existing `normalize` util's traversal loop to override values while normalizing them. The core loop was refactored out of the normalize function and is also utilized by the `getDefaults()` function to merge overrides while replacing default arrays (rather than concat arrays with the normal merge behavior).
To validate core configuration options with `config:validate`, the core …
> 🐛 Fix config merging

- packages/client/src/utils.js
- packages/client/test/client.test.js
- packages/client/test/helper.js
The old `percy-js/client` library had retry handlers for specific request error codes. Unsure how/why they were dropped during the transition, but this PR adds them back with a `shouldRetryRequest` helper that is utilized within request error handlers.
> ✨ Retry specific request error codes

- packages/core/src/percy.js
- packages/core/test/.eslintrc
- packages/core/test/percy.test.js
When using the `exec:start` command it downloads a browser if needed just like the `exec` command. However, the `exec` command waits for the start process to resolve directly before calling the provided command while the user/SDK is left to check this themselves when using `exec:start`. The healthcheck endpoint resolves when the server is listening, but the server is actually listening before a browser is downloaded and the process is actually ready.
Move the server start process to after the browser launch and build creation processes. This ensures that the server, and therefore the healthcheck endpoint, will only resolve when actually ready.
To test this, the various methods are stubbed to capture a timestamp and the resulting timestamps are compared after starting the whole process.
> 🐛 Start server after launching a browser and creating a build

- packages/core/src/percy.js
- packages/core/test/percy.test.js
- packages/sdk-utils/README.md
- packages/sdk-utils/index.js
- packages/sdk-utils/test/index.test.js
Removing the path from the address will make it less error-prone to customize by not requiring that the env var ends in `/percy`
> ♻ Remove path from cli api address

- packages/dom/src/serialize-cssom.js
Sometimes `innerText` can be undefined which causes this function to error when it should report true. This check is present in the old serialization script in agent, but it couldn't be confirmed if it was needed since I'm not quite sure how to replicate that behavior to test it.
> 🐛 Fix CSSOM check

- packages/core/src/percy-css.js
- packages/core/test/percy-css.test.js
When the Percy CSS file is injected into the DOM, it is injected as a root-level asset. However, when uploaded, the resource URL is defined relative to the root resource URL which may contain an additional pathname. 
Construct the Percy CSS file's URL from the root URL's origin rather than the entire root URL.
> 🐛 Upload Percy CSS as a root asset

- packages/env/src/environment.js
- packages/env/test/appveyor.test.js
- packages/env/test/azure.test.js
- packages/env/test/bitbucket.test.js
- packages/env/test/buildkite.test.js
- packages/env/test/circle.test.js
- packages/env/test/codeship.test.js
- packages/env/test/defaults.test.js
- packages/env/test/drone.test.js
- packages/env/test/gitlab.test.js
- packages/env/test/heroku.test.js
- packages/env/test/jenkins.test.js
- packages/env/test/probo.test.js
- packages/env/test/semaphore.test.js
- packages/env/test/travis.test.js
This fixes a few minor issues with parallel total and nonce collection
Parallel total - `parseInt` does not throw but can return NaN, Infinity, or hex values; which should be checked and removed if present.
Parallel nonce - the API does not like it when a nonce is provided without a total, which happens by default when somebody has parallel CI jobs even without parallel Percy builds.
The total collection was moved before the nonce. If there is no total, do no collect the nonce. This will suppress parallel errors when the user is not providing the parallel total option. If they do supply a parallel total and the nonce is missing from their environment, the error will still correctly occur.
> 🐛 @percy/env parallel fixes

- packages/cli-build/src/index.js
- packages/cli-config/src/index.js
- packages/cli-exec/src/index.js
- packages/cli-snapshot/src/index.js
- packages/cli-upload/src/index.js
This allows for invoking commands via Node scripts without needing to invoke a subprocess.
These are exported via the commonjs syntax to avoid having to destructure the `default` property when used without ES modules.
> ✨ Export CLI commands

- packages/cli-upload/src/resources.js
- packages/cli-upload/test/upload.test.js
The API expects resource URLs to either be a fully qualified URL or an absolute path and does not accept relative URLs.
Add a leading `/` to the image upload's root URL and add an expectation for it in the existing success test.
> 🐛 Use absolute path for image upload root URL

- packages/cli-command/README.md
- packages/cli-command/src/flags.js
- packages/cli-command/test/command.test.js
- packages/cli-command/types/index.d.ts
- packages/cli-command/types/index.test-d.ts
- packages/cli-exec/README.md
- packages/cli-snapshot/README.md
- packages/core/README.md
- packages/core/src/config.js
- packages/core/src/discoverer.js
- packages/core/test/asset-discovery.test.js
- packages/core/types/index.d.ts
- packages/core/types/index.test-d.ts
As we hone in on the final v1 of the CLI, we're working out the last breaking changes we want to live with. None of the other flags mention `asset`, so we decided to align this flag with the others (since it's already breaking for `@percy/agent`'s `--cache-responses` flag).
> 💥 Rename `--disable-asset-cache` flag to `--disable-cache`

- packages/sdk-utils/index.js
A logger is a singleton, but tests teardown and recreate that singleton for a clean environment. When a logging group is created, it is bound to the singleton instance at the time of creation. Creating a group at the root level, like in the sdk-utils, causes it to forever be bound to that initial instance and not be effected by test setup. By lazily creating the logging group, we can be assured that the test environment will be cleaned up without requiring a re-require of the file where the logger is created.
> ✨ Lazily create sdk-util logger for testing purposes

- packages/dom/karma.conf.js
- packages/dom/package.json
- packages/dom/rollup.config.js
- packages/dom/test/helpers.js
- packages/dom/test/index.js
- packages/dom/test/serialize-canvas.test.js
- packages/dom/test/serialize-css.test.js
- packages/dom/test/serialize-dom.test.js
- packages/dom/test/serialize-frames.test.js
- packages/dom/test/serialize-inputs.test.js
- yarn.lock
Currently, `@percy/dom` is compiled with Webpack. When tests run, a Karma plugin also compiles tests with Webpack. Since Webpack 5.0, some default node polyfills were removed causing test failures and we now have to polyfill them ourselves. Additionally, a recent Karma update prevents it from running when extraneous flags are provided (`--coverage`).
Karma config was updated to use an environment variable rather than rely on the extra flag. Since we have to polyfill node modules anyway, Webpack was removed in favor of Rollup which produces smaller, more readable bundles and is preferred for bundling libraries whereas Webpack is preferred for bundling applications.
Rather than fighting with `expect` and `cheerio` to work in-browser, small alternatives are used in `@percy/dom` tests. …
> ✅ Fix @percy/dom Karma and Webpack issues

- packages/core/src/utils/install-browser.js
This takes the guesswork out of determining the browser executable path. The current guesswork is accurate for Chromium, but when this script is utilized to download other browsers, the executable location can be difficult to determine based on the filename alone. For example, the archive for Firefox on Linux is `firefox 73.0.tar.bz2` and when getting the executable path it guesses `firefox 73.0.tar/firefox` even though the actual archive unzips to `firefox/firefox`.
By removing the guesswork and being explicit, we can avoid OS/Browser archive name inconsistencies.
> ♻ Adjust how the browser download script determines executable path

- packages/core/src/utils/wait-for.js
The `waitFor` helper inside of `@percy/core` didn't appear to have any issues, however the option `ensure` was actually meant to be `idle` as evidence by uses of an `idle` option elsewhere in the codebase. This caused those options to be ignored when they should not have been. This was likely missed due to requiring coverage ignore the function as it gets injected into the browser where coverage variables are lost.
Fixing this might help with some flakey tests. 🤔
> 🐛 Fix wait-for helper idle option

- packages/logger/src/colors.js
- packages/logger/src/logger.js
- packages/logger/test/helper.js
- packages/logger/test/index.test.js
This adds an additional detail to debug logs which can come in handy when debugging: elapsed time. The time between debug logs can be a useful clue in finding the root cause of issues.
The logger test helper will automatically remove the elapsed time so other debug tests do not need to be updated. However, there is an option to leave elapsed time alone in case it is something that needs to be tested (such as within logger tests themselves). The log dump test helper was also updated to include the elapsed time between log entries.
> ✨ Add elapsed time to debug messages

- package.json
- packages/core/src/discovery/browser.js
- packages/core/src/discovery/discoverer.js
- packages/core/src/discovery/network.js
- packages/core/src/discovery/page.js
- packages/core/src/percy.js
- packages/core/src/utils/install-browser.js
- packages/core/test/capture.test.js
- scripts/chromium-revision
- scripts/release-notes
This updates the version of Chromium downloaded and used by asset discovery to Chrome 87.0.4280, which matches the next version that will be used in Percy's own rendering environment.
With this specific version of Chromium, the revisions are varied across all platforms. To make finding these revisions easier than the manual process, I automated it with a script. I also removed the old release-notes script since this repo uses a release-drafting action.
If authenticated with GitHub, the script could be modified to search a range of several versions to find a close match that has only one revision across all platforms. It could also be improved with GitHub's GraphQL API to search for the tag in a single query rather than paginating all tags for the Chromium repo. But that can be a future …
> ⬆ Upgrade Chromium 78 to 87

- packages/cli-config/src/commands/config/migrate.js
- packages/cli-config/test/migrate.test.js
- packages/cli-snapshot/package.json
- packages/cli-snapshot/src/config.js
- packages/cli-snapshot/src/hooks/init.js
- packages/cli-snapshot/test/unit/config.test.js
- packages/cli-upload/package.json
- packages/cli-upload/src/config.js
- packages/cli-upload/src/hooks/init.js
- packages/cli-upload/test/unit/config.test.js
- packages/config/src/index.js
- packages/config/src/load.js
- packages/config/src/migrate.js
- packages/config/test/index.test.js
- packages/core/package.json
- packages/core/src/config.js
- packages/core/src/index.js
- packages/core/src/percy.js
- packages/core/test/unit/config.test.js
- packages/core/test/unit/queue.test.js
Currently, if a v1 config file is detected, it's configuration options are discarded. In order for config files to work with `@percy/cli`, the config file needs to be in a v2 format which can be migrated to using the `config:migrate` command. This PR breaks up the migration logic from the command and moves it alongside respective config schemas, allowing the `@percy/config` package to migrate configuration options on-the-fly.
- The `config:migrate` command no longer houses it's own migration logic. This has been split alongside respective schemas. This allows migration and the migrate command to be extensible just like the schema and validate command is.
- The new migration function can be registered with `PercyConfig.addMigration` which mirrors `PercyConfig.addSchema`. The migration …
> ✨ Backwards compatibility with v1 config

- packages/cli-config/package.json
- packages/cli-config/src/commands/config/migrate.js
- packages/config/package.json
- packages/config/src/load.js
This dependency has many small helpers based on two single sync and async helpers. In both places we use this dependency, we only use it to check if a filepath is a directory synchronously. This is done by the depdendency wrapping `fs.statSync().isDirectory()` in a try-catch to catch `ENOENT` errors. In both places we use this helper, we are already wrapping calls in a try-catch, so we can swap out this dependency entirely with the native method. 
However this dependency will still exist in our tree, as I believe `cosmiconfig` depends on it.
> ➖ Remove path-type dependency

- packages/config/src/index.js
- packages/config/src/normalize.js
- packages/core/src/server.js
- packages/core/test/server.test.js
- packages/dom/src/serialize-dom.js
Currently, snapshot options via the CLI API are only accepted as camelCase options. In some languages, this goes against the languages own syntax standards such as `snake_case` variables and options. Allowing the snapshot API endpoint to accept any style of options removes the conversion responsibility from the SDK.
The `@percy/config` package already has a `normalize` function that removes empty values and converts kebab-case options to camelCase. This has been modified to also convert snake_case options. The `normalize` function is now exported with the package so that the `@percy/core` server can utilize it for converting snapshot API options.
> ✨ Accept all option syntax styles

- packages/dom/karma.conf.js
- packages/dom/rollup.config.js
- packages/dom/src/index.js
The `@percy/dom` package uses a UMD format which assigns exports to a `globalThis` variable when in a browser environment. However, if the implementation of `globalThis` is incorrect (mozilla/geckodriver#1798), the `PercyDOM` object is not correctly carried forward into other script executions where the DOM is meant to be serialized.
This PR aims to work around this issue by checking if `window` and `globalThis` are not equal to each other (which technically should be impossible under normal circumstances). If they are not equal, the library adds itself to `window` ahead of the eventual UMD dance.
While testing this, I also noticed that babel helpers were inlined multiple times. Updating this setting to `bundled` will ensure they are only bundled once in the final output.
> 🐛 Work around incorrect global context in @percy/dom

- packages/client/src/client.js
- packages/client/test/client.test.js
This allows SDKs and other consumers of `@percy/client` to set multiple client or environment info at a time by providing an array instead of requiring an already formatted string. Rather than use arrays and manually checking for uniqueness, we can use Sets which are inherently unique.
> ✨ Allow setting multiple client or environment info at a time

- packages/cli-config/src/commands/config/migrate.js
- packages/config/src/load.js
- packages/config/src/normalize.js
- packages/config/test/index.test.js
The yaml config format typically prefers keys to be kebab-cased. Our docs even show the yaml config files with kebab-cased keys. With config migration moved into `@percy/config`, it always normalizes keys as camelCased. We should always prefer kebab-cased when migrating to a yaml format.
Allow normalize to accept options other than `overrides`, including an option to convert keys to kebab-cased rather than camelCase. The new kebab-case function will convert both camelCase and snake_case, similarly to how the camelCase function converts both kebab-case and snake_case. In order to account for edge case camelizations such as `CSS` and `JavaScript`, the edge cases map was utilized to covert keys the other direction as well to avoid accidentally adding dashes where there shouldn't be.
> ✨ Prefer kebab-case for yaml config files

- packages/core/src/discovery/browser.js
The browser executable option is typically more useful as a CI environment variable rather than a config option that is carried forward to various environments.
> ✨ Accept browser executable env var

- .github/workflows/test.yml
It appears that `@percy/logger` tests slipped by without being added to the CI tests workflow. This PR adds the package to the workflow so that its tests are run for each commit.
> 💚 Add @percy/logger to CI test workflow

- packages/cli-config/src/commands/config/migrate.js
- packages/cli-config/test/migrate.test.js
- packages/config/src/stringify.js
- packages/config/test/index.test.js
Although I haven't noticed any issues with the string replacement method, it feels like it has the potential to be buggy. I think the initial intention was to avoid having to parse the entire json file, but in reality parsing a single package.json file is very quick.
While making this change, I noticed that the parsing and re-stringifying causes the file to lose it's line ending. I decided to add this line ending to the config stringify output so it will be consistent for all formats.
> ♻️ Migrate to package.json config without string replacement

- .github/workflows/test.yml
- packages/cli/bin/run
- packages/cli/index.js
- packages/cli/package.json
- packages/cli/test/.eslintrc
- packages/cli/test/helpers.js
- packages/cli/test/index.test.js
- yarn.lock
With `@oclif/plugin-plugins`, the user is _required_ to use the various `plugin:*` commands in order to use plugins with the CLI. This means that if the CLI and a CLI plugin are both dependencies, the plugin will **not** automatically be associated with the CLI until the user runs the appropriate `plugin:*` command.
Before calling the first OCLIF entry point within `@percy/cli`, we can search through `node_modules` for `@percy/*` and `percy-cli-*` packages to append to `@percy/cli`'s list of plugins. 
This is similar but distinctly different from how the `@oclif/plugins-plugin` handles plugins. With the official plugin, it has its own dependency on `yarn` which manages plugin package, and registers plugins via editing a global data directory's `package.json` file associated with the CLI …
> ✨ Autoload plugins

- packages/cli/index.js
- packages/cli/test/helpers.js
When the CLI is linked or eventually distributed outside of NPM, it might not always reside within a project or global `node_modules`. In these cases, it should autoload plugins from within its own `node_modules`. This will enable linking plugins to the linked CLI and also allow future iterations to install plugins into the CLIs own `node_modules`.
This is labeled as a bug although it doesn't necessarily fix anything because it would be one if we distributed the CLI outside of NPM.
> 🐛 Improve plugin autoloading

- packages/cli-exec/test/start.test.js
- packages/core/test/capture.test.js
- packages/dom/test/serialize-frames.test.js
Some tests are flakey. This PR aims to unflake them all
Sometimes a frame may take longer than expected to load. Even the JS only frame may load after modifying the frame document causing that test to flake. On windows, frames can take even longer to load than 3s, so the wait timeout was upped to 5s and the hook timeout was removed.
Expected: `Network error: Page closed`
Received: `Protocol error (Runtime.callFunctionOn): Page closed`
Received message suggests that the page is sometimes closing either during the provided script execution or after the second network idle during DOM serialization script execution.
It's possible for the test to continue after an asset has been accessed but before the request has been intercepted causing it to flake. Delaying when asset access is detected …
> ✅ Fix flakey tests

- packages/cli/index.js
- packages/cli/test/helpers.js
- packages/cli/test/index.test.js
If the directories being searched in do not exist, those errors should be silently ignored since no plugins can exist in a non-existent directory.
> 🐛 Catch autoload directory errors

- packages/core/src/server.js
- packages/core/test/server.test.js
When accessing the old DOM library server endpoint (that `@percy/agent` uses) we log a deprecation message. The previous deprecation message is too technical and won't make sense unless you know how the SDKs piece together. The new one aims to be more actionable.
> ♻️ Update `agent.js` deprecation message to be user friendly

- packages/config/src/normalize.js
- packages/config/test/index.test.js
Currently the normalize method traverses nested objects, including `request-headers`, and converts the casing of the keys to be predictable. Request header keys however, should not be converted and key casing should be left as-is.
Add a `skipMerge` array to the merge helper that will not traverse the object any further if the key is present in the array. Currently, the only key to skip is `request-headers`.
> 🐛 Fix normalized config request-headers

- packages/cli-config/src/commands/config/migrate.js
- packages/cli-config/test/migrate.test.js
- packages/config/src/index.js
- packages/config/src/load.js
- packages/config/test/index.test.js
This pattern is used in `@percy/config`, `@percy/cli-config`, and `@percy/migrate`; so making it a helper will DRY up those places.
I also removed a redundant error message as the real error gets printed anyway.
> ✨ Add config search method

- packages/core/package.json
- packages/core/src/discovery/browser.js
While chasing an issue on Windows where the `@percy/cli-exec` test suite hangs, some changes were made in an attempt to ensure the browser process was being handled correctly. While this ultimately didn't fix the issue on Windows, I do think these are good changes that should be adopted regardless.
- Add check if browser is already closed
- Use cross-spawn to spawn browsers
- Do not spawn detached browser in Windows
- Always kill browser process when able to
> ♻ Improve browser process handling

- .github/workflows/windows.yml
- packages/cli-config/test/create.test.js
- packages/cli-config/test/migrate.test.js
- packages/cli-config/test/validate.test.js
- packages/cli-exec/test/exec.test.js
- packages/config/test/index.test.js
- packages/core/src/discovery/browser.js
- packages/core/src/utils/install-browser.js
- packages/core/test/helpers/index.js
- packages/core/test/percy.test.js
- packages/dom/package.json
- scripts/babel-register.js
- yarn.lock
This PR adds a Windows CI workflow and fixes a few issues that cause test failures in Windows environments. For the most part, this involves using path helpers rather than hardcoding path separators.
Windows also has issues with atomic file operations. Errors from `rimraf` are now ignored in `@percy/core` tests, and the browser installation test was removed due to it also needing to delete files. Since this test was removed, browser installation coverage became zero which prompted a coverage ignore statement to be added. Ultimately, the tests need the browser to be downloaded in order to work, so I'm confident in removing coverage from this file since it is technically tested before any relevant tests run.
One final _hanging_ issue was that `@percy/cli-exec` tests were hanging, but only …
> 💚 Add Windows workflow

- packages/core/package.json
The addition to include the post-install script in the packaged files was missed in #206
> 🐛 Include post-install script in packaged files

- packages/core/post-install.js
The post-install script checks for a test directory to determine if it is being run in development. This package exports a test helper which means the test directory is also present in production. The src files should never be included, so should be a much safer check.
> 🐛 Check src directory for post-install

- packages/cli-exec/README.md
- packages/cli-exec/src/commands/exec/index.js
- packages/cli-exec/test/exec.test.js
Rather than requiring the user set an environment variable to determine if a build is a partial build, we can set the environment variable automatically when provided a `--partial` flag.
This brought up a question in my mind about the `--parallel` flag's short version, `-p`. Could be confusing now with a second "p" argument; should we remove the parallel shorthand to avoid confusion before leaving beta?
> ✨ Add exec partial build flag

- packages/dom/src/index.js
Nightmare/electron envs don't have `globalThis` defined, which errors and breaks snapshots. This wraps a try/catch around it to stop that from happening
> 🐛  Catch any errors that arise from `globalThis` in the DOM libary

- scripts/build.js
- scripts/test.js
If the first run of a script fails, it never gets to the watch logic. The error handler also called `process.exit`, which it should not do when watching.
Since test runners like to assume they have control over the process, when run together they were forked. They are now always forked since the watch process needs to control its own process.
> 🔨 Fix script watching

- rollup.config.js
In response to #232, I forgot that `globalThis` is also referenced in build bundles.
> 🐛 Catch undefined globalThis in bundles

- karma.config.js
- package.json
- packages/core/test/helpers/index.js
- scripts/test-helpers.js
While debugging some failing tests, I noticed that the failed test check used to produce log dumps did not work due to the recent refactor to Jasmine. Jasmine does not have a way to access the current test from within a hook, but it did feel more proper to add it as a shared reporter in the common test helpers file. Since this file is also loaded in browser environments, I had to add catches around reading the environment variable and also set said variable in an alternate way for karma tests since the common test helpers do not get bundled with rollup.
> ✅ Fix test log debugging

- packages/dom/src/index.js
- rollup.config.js
Sometimes modules or exports are polyfilled causing the UMD bundle to not attach the DOM script to the global scope. Since this scope issue seems to keep coming up, let's always set the serialize function globally when the window object is defined.
I also updated the bundle intro to use `typeof` rather than `try-catch`.
> 🐛 Force @percy/dom globalization

- .gitignore
- package.json
- packages/dom/package.json
- packages/dom/src/index.js
- packages/logger/package.json
- packages/logger/src/index.js
- rollup.config.js
- scripts/build.js
Currently, `@percy/dom` and `@percy/logger` have UMD browser bundles. When injecting `@percy/dom` in different environments, we've found that it sometimes didn't properly attach itself to the context due to factors such as inconsistent `globalThis` implementations or re-compiling causing the UMD code to assume a commonjs environment. 
We've worked around these issues in `@percy/dom` by forcefully setting a global variable when a `window` context is available. However, these bundles should only ever be consumed in a browser environment, resulting in that window global should _always_ be set. Rather than support every module format, we can use an IIFE since we know the code will only ever be executed in a browser. To support other bundlers consuming our bundle, we can conditionally check …
> ✨ Better browser bundles

- packages/logger/test/helpers.js
- scripts/test-helpers.js
Log dumping was broken in a couple of ways. The actual `dump` method had a member typo which always returned undefined causing the function to abort. Even if it were defined it would log the warning even with zero logs. Finally, the failed test reporter did not work in browser environments since this file does not get bundled. The reporter now references the possible window globals when in a browser context.
Depends on #252
> ✅ Fix test log dumping

- packages/logger/src/logger.js
- packages/logger/test/remote.test.js
The cleanup function for remote logging attempted to remove event listeners, however the events were registered with anonymous functions. By providing the intended function, the argument must be changed along with its usage as the timeout callback.
This bug doesn't necessarily effect anything as the socket lives as long as the process anyway unless it fails to connect. However this code should at least be corrected.
I also experienced an instance where a WebSocket error within the browser may not contain an `error` property. So a fallback message is used for error events without said property (and an accompanying test was added).
Depends on #252 & #253
> 🐛 Fix remote logger cleanup

- packages/core/src/server.js
- packages/core/test/server.test.js
With most responses, all headers in the request response are included in the response object. In browsers however, the `Access-Control-Expose-Headers` header is strictly respected and if that header does not exist, or the desired header is not defined within it, the response object will not contain all response headers.
Adding this header will allow SDKs within browsers to access the version header exposed by the local Percy server API.
Depends on #252, #253, & #254
> 🐛 Expose version header for CORS

- packages/logger/test/index.test.js
A test logs, waits 100ms to log again, then asserts that the correct elapsed time was printed. Sometimes this logger test shows the elapsed time a little out of range of 100-109ms, so the check is loosened to 90-119ms. We're not really testing speed here, just that the elapsed time prints.
> ✅ Fix flakey logger test

- packages/cli-exec/src/commands/exec/index.js
- packages/core/src/percy.js
- packages/core/test/percy.test.js
- packages/sdk-utils/README.md
- packages/sdk-utils/index.js
- packages/sdk-utils/test/helpers.js
- packages/sdk-utils/test/index.test.js
Initially, the `PERCY_CLI_API` environment variable was named so because it was the CLI that set that variable for SDKs to consume. However, that API address can still be consumed by SDKs without the CLI. In reality, this value comes from the core server, so it's name should reflect that.
`PERCY_SERVER_ADDRESS` was chosen as it is pretty descriptive in that the variable contains the address of the local Percy server. However, I'm open to other suggestions.  <img alt="bikeshed" title="bikeshed" height="20px" src="https://emojis.slackmojis.com/emojis/images/1515784750/3372/bikeshed.png"/>
Since this variable is only set by the CLI, and official SDKs consume this internally, I wouldn't count this as breaking for our own SDKs. If the user was using the `--port` option (not likely), it will …
> ♻️ Rename server address method / environment variable

- packages/logger/src/logger.js
- packages/logger/src/util.js
- packages/logger/test/remote.test.js
In addition to a WebSocket Server, the node `ws` library provides a way for Node environments to use a `WebSocket` client class similar to browser environments. Even though a `ws` WebSocket has identical event names to its browser counterpart, events in Node typically do not emit Event objects like in browsers. This makes it so our agnostic code must handle both types of event listeners.
Rather than checking event listener arguments to determine if a value or event object was provided, we can use `on<eventname>` handler counterparts which are called by `ws` in _exactly_ the same way browser WebSocket handlers are called — with an event object. The main difference between listeners and handlers is that multiple event handlers cannot be registered at the same time. However, we are not …
> 🐛 Fix cross-env remote logging handlers

- rollup.config.js
Currently, our bundles require `regeneratorRuntime` to be present in the environment in order for async functions to work (`@percy/logger` now, `@percy/sdk-utils` soon). This is because they are bundled for the "last 2 versions" of browsers including browsers with very little usage or browsers that might not be maintained.
The "defaults" browser target option also targets the last 2 versions, but further filters the list based on usage and also includes Firefox ESR and a particular browser that is soon to be no longer maintained. This option would still require the regenerator runtime for bundles with async functions.
Rather than bundle based on browsers, we can bundle based on feature support. In addition to the last 2 versions, the target list can be further filtered by support for …
> 🔨 Only bundle for browsers that support async/await

- packages/logger/test/helpers.js
- packages/logger/test/index.test.js
We currently use the `spyOn` helper from jasmine to spy on browser logs. This works great for tests within this repo which also uses Jasmine, however it does not work so well outside of Jasmine where `spyOn` isn't typically globally available.
Add our own small `spy` helper within this util that takes care of the spying regardless of the testing framework. The expectation API changed and tests updated since we are no longer using a built-in spy, however those changes were small.
> ✅ Make @percy/logger test helper framework agnostic

- babel.config.js
- packages/logger/test/helpers.js
The optional chaining syntax (`?.`) is supported in Node 14, but not Node 12. So it was missed when developing `@percy/logger` test helpers. Babel config exists that is meant to ignore distributed files to raise such issues during CI, however it was not configured correctly.
This updates the babel config to use the current working directory in combination with a package's distributed files list. Unfortunately, this meant that development aliases no longer existed for some of these files. To accommodate development aliases, only the base config is not applied to distributed files. This makes it so no ES features are accidentally transpiled in these files and tests will now warn when such a file has been encountered.
Now that this is fixed, the offending `?.` was also fixed in …
> 🐛 Fix @percy/logger test helper unsupported syntax

- rollup.config.js
Adds support for AMD format in bundles to allow imports in those environments (such as Ember).
> ✨ Add AMD support to bundles

- packages/sdk-utils/src/request.js
- packages/sdk-utils/test/server.js
Two small `@percy/sdk-utils` improvements.
- Grab fetch references before they might be mocked
- Clone the document during mock dom transformations
> ✨ sdk-utils improvements

- packages/core/test/server.test.js
- packages/logger/src/logger.js
- packages/logger/test/remote.test.js
- packages/sdk-utils/src/percy-enabled.js
- packages/sdk-utils/test/index.test.js
Sometimes, WebSocket errors can come from the constructor itself which is defined outside the scope of the logger. Rather than having extra error handling, we can have the logger accept a socket creator function and wrap it with the existing error handling.
Usage of the `remote` method was updated in `@percy/sdk-utils` as well as other tests.
> 🐛 Account for logger websocket synchrony

- packages/env/src/environment.js
- packages/env/test/azure.test.js
Copying over the same change from https://github.com/percy/percy-js/pull/257
Add support for Azure Pipelines change in pull request number environment variable
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables-devops-services
> **System.PullRequest.PullRequestId**
> 
> The ID of the pull request that caused this build. For example: 17. (This variable is initialized only if the build ran because of a Git PR affected by a branch policy).
> **System.PullRequest.PullRequestNumber**
> 
> The number of the pull request that caused this build. This variable  is populated for pull requests from GitHub which have a different pull  request ID and pull request number. This variable is only available in a  YAML pipeline if the PR is a …
> ✨ Add Azure Pipelines env var for pull request number

- packages/client/src/client.js
- packages/env/src/environment.js
- packages/env/src/utils.js
- packages/env/test/github.test.js
- packages/env/test/helpers.js
This adds better support for GH Actions by reading from the event payload file created in workflows by their corresponding webhook events.
In our official GH Actions, we use `@actions/github` to read environment information such as the PR number and branch name. This package (and specifically the properties used in our actions) are actually a thin wrapper around [reading from the file](https://github.com/actions/toolkit/blob/fc005283374f1cea5e03ea1caf959cd9ff12fdc2/packages/github/src/context.ts#L27-L36) located at `GITHUB_EVENT_PATH`.
We can eliminate the need for specific actions, and that library, by reading from this event file directly ourselves.
This is done with a new util function. The existing utils were all `git` based, so the file was named `git.js`. However with the addition …
> ✨ Better GitHub Action env support

- packages/logger/src/logger.js
- packages/logger/test/index.test.js
The printed debug messages are meant to show the time elapsed between logs. However, when it was implemented by saving the last timestamp accidentally with a logical or assignment, which means that it will only ever be set on the first log and never updated again. Removing the `||` fixes the accumulative timestamp and will show proper elapsed-between timestamps.
This might also relate to this specific test being flakey in CI. Probably because the time between the first log and last log was slow even though we only want to test the time between the last log and the previous log. An additional log was added to test that the timestamp is **not** accumulative.
> 🐛 Fix printed debug timestamps

- rollup.config.js
AMD bundles have two syntaxes: `define(id, deps[], factory)` and `define(deps[], factory)` (filename becomes the ID). We were inadvertently combing the syntaxes into `define([id], factory)`. 
While our incorrect syntax is technically valid (circular dep on itself), we had another compounding issue. We were using `pkg.name` for the ID even when the package contains multiple bundles (like for test helpers).
While requiring the AMD bundle in Ember SDK tests, this compounded issue caused the test helpers to re-require the main package bundle which caused duplicate bundles to be included causing the test helpers to use outdated references.
This PR simply removes AMD deps from our bundles since our bundles do not actually contain external deps.
> 🐛 Fix AMD bundle

- packages/core/src/install.js
- packages/core/test/unit/install.test.js
The `@percy/core` package [manages chromium version](https://github.com/percy/cli/blob/master/packages/core/src/install.js#L18-L23) on its own when no executables provided, so there is no versions mismatch possible in this scenario. However, when the `PERCY_BROWSER_EXECUTABLE` env var is set to point to a chromium executable it becomes difficult to manage the chromium version and keep it aligned with the ones that the library is supposed to work with. Especially, when the dependency definition in `package.json` file is set like:
```
{
...
"peerDependencies": {
"@percy/core": "*",
},
...
}
```
Expose chromium versions to be able to assert that the local one fits the requirement. For example:
```js
const { chromium } = require('@percy/core/dist/install');
assert.equal(
'812847', …
```
> ✨ Expose used chrome versions

- packages/cli-build/src/commands/build/wait.js
The `build:wait` command requires a full org/project slug and the example only gave the project slug (that will error). This PR updates the example to give an org/project slug.
> ♻️ Update `build:wait` example output

- packages/cli-config/test/migrate.test.js
- packages/cli-snapshot/src/config.js
- packages/cli-snapshot/test/unit/config.test.js
- packages/cli-upload/src/config.js
- packages/cli-upload/test/unit/config.test.js
- packages/config/src/load.js
- packages/config/src/migrate.js
- packages/config/test/index.test.js
- packages/core/src/config.js
- packages/core/test/unit/config.test.js
This improves the config migration pattern to support migrating deprecated options within the current config version. To support this, migrations are always performed. As such, they no longer result in a fresh object, but instead mutate the provided config using util functions. Internally, the provided config is never a reference in danger of harmful mutations.
Previously, only a `set` util was provided. Now there is also `map` and `del` which can map and delete config options respectively. A fresh logger is also provided so migrations can log deprecation warnings.
This shouldn't break anything externally unless a 3rd party CLI plugin is already relying on beta config migration patterns.
> ✨ Improved config migrate

- packages/core/src/discovery/browser.js
- packages/core/src/discovery/discoverer.js
- packages/core/src/discovery/page.js
- packages/core/src/utils/url.js
- packages/core/test/asset-discovery.test.js
- packages/core/types/index.d.ts
- packages/core/types/index.test-d.ts
This adds `disableCache` and `allowedHostnames` to the new per-snapshot `discovery` options. Some refactoring was done to make future options much simpler to add:
- At the `percy.snapshot` method, specific options (including per-snapshot discovery options) are passed along to the `discoverer.gatherResources` method. This method then explicitly provides other methods with appropriate options; such as providing size/javascript/network options to the `page` method and discovery options to the various discovery handlers.
Now, `gatherResources` and subsequent intermediary functions will only reference options as needed and then pass all other options along down the call chain. Any option can then be plucked where needed — such as these new discovery options only needing to be added to the …
> ✨ Add per-snapshot discovery cache and hostnames options

- packages/core/src/config.js
- packages/core/src/discovery/page.js
- packages/core/test/asset-discovery.test.js
Adds the ability to set a custom user-agent string via a config file or per snapshot option, `discovery.userAgent`.
By default, it will use the normal Chrome user agent without the `Headless` part in an attempt to prevent servers from blocking headless requests from asset discovery. SDKs can gather a more suitable user agent from the browser where the DOM was captured from and provide this user agent to the CLI automatically.
> ✨ Allow setting discoverer user-agent

- packages/dom/src/serialize-frames.js
- packages/dom/test/serialize-frames.test.js
It seems that in some circumstances an iframe's `documentElement` may be null which then causes serialization errors. After some research, it appears this property may be null when accessed before the document has finished loading, if the document does not contain an element such as empty documents, or if a script purposefully unsets the property.
Add another check, in addition to the `contentDocument` check, for `documentElement`. Tests are performed by unsetting the property before serialization.
Fixes #329
> 🐛 Do not serialize frames without document elements

- packages/client/src/request.js
- packages/core/src/install.js
While the URL `host` is supposed to contain the `hostname` and `port`, it actually does not always. Similarly, sometimes `port` can be missing as well. In the proxy agent, we were relying on `host`,  but need to actually use `hostname` and `port` separately while also using a default port. This default port does get picked up by coverage since our `localhost` test URLs use specific ports.
This PR also adds proxy agent utilization to browser installation to allow browser downloads to flow through proxies as well.
> 🐛 Default host port for proxy requests

- packages/cli-command/src/command.js
- packages/cli-command/test/command.test.js
I've noticed (especially without a config file present) that the config debug logs will log twice. This is because we load the config in the CLI using `this.percyrc()` and core also auto loads the config itself.
By automatically setting the `config: false` option in `this.percyrc()`, when passed to core it will not reload the config file and instead merge defaults with the provided options already loaded from the file.
> 🐛 Stop core config reloading when already loaded via the CLI

- packages/client/src/request.js
- packages/client/src/utils.js
When utilizing this util outside of client, it can be useful to configure retry options. These options are available, but never used by client itself since the defaults are acceptable.
> ✨ Add retry options to internal request util

- packages/client/src/client.js
- packages/client/test/proxy.test.js
In the world of `@percy/agent`, setting the `PERCY_API` environment variable allowed you to override the URL used by client to communicate with the Percy API. That behavior was lost when moving to the new `@percy/cli` world, but can be useful when manually testing or interacting with a local development API.
With client's proxy agent, we indiscriminately proxy all API requests through HTTPS since our production API server is guaranteed to be HTTPS. However, with the potential to change the API URL to a locally hosted URL, it might not always be HTTPS. So we need to check the protocol of the API URL to disable the HTTPS proxy agent and allow the `request` util to default to the appropriate agent based on the request's protocol.
This shouldn't be used by end users, so `PERCY_API` felt too …
> ✨ Allow setting client's API url via an environment variable

- packages/core/src/percy.js
- packages/core/src/queue.js
With recent changes from #369, when `config.discovery.concurrency` is not defined, it is still being set on the queue causing the default of 5 to be removed. This enables infinite concurrency which is not what we want since it causes a huge slowdown as more and more resources are consumed in parallel
> 🐛 Fix unintentionally removing the default queue concurrency

- packages/core/src/discovery.js
- packages/core/src/network.js
- packages/core/src/page.js
- packages/core/src/percy.js
- packages/core/src/queue.js
- packages/core/test/unit/queue.test.js
Following #369 and subsequently #372, I've since found a couple other minor thing that need to be tweaked.
- In agent, up to 10 browser pages were pooled to be running at once. It was lowered in the CLI since moving to a proper queue with a concurrency. Now that queue performance has gotten much better, let's up it to 10 again. Even in previous versions of the CLI up to 10 browser pages could be running when using the capture method, so being able to set this more accurately is a win from #369.
- Rename `queue.pause()` to `queue.stop()` (🚲 🏠). Pause implies that there is still more to run, while stop implies that it won't run regardless if there is more to run. Stop also feels more complimentary to `run()`.
- Add ability for `close()` to abort. This will stop and clear the queue while …
> ♻️ Post core refactor tweaks

- packages/cli-build/src/commands/build/wait.js
- packages/cli-build/test/wait.test.js
- packages/client/src/client.js
- packages/core/README.md
- packages/core/package.json
- packages/core/src/install.js
- packages/core/src/percy.js
- packages/core/src/queue.js
- packages/core/test/percy.test.js
- packages/core/test/unit/install.test.js
- packages/logger/src/browser.js
- packages/logger/src/logger.js
- packages/logger/test/helpers.js
- packages/logger/test/logger.test.js
- scripts/chromium-revision
- yarn.lock
There are two logs in particular that would be nice to have some progress associated with them. The processing snapshot queue log and the snapshot uploading queue log.
When SDKs such as Storybook or the snapshot command quickly take and process snapshots via asset discovery, the end result could be waiting for hundreds of snapshots to upload. To prevent clogging up processes with hundreds of in-flight requests at once, uploads are queued just as asset discovery is. 
This results in a single log at the end of snapshot processing, before finalizing the build, when snapshots are uploading: `Waiting for X snapshots to finish uploading`. With #369, the message was changed to be more generic: `Uploading snapshots...`. Which is arguably less helpful, but in either case the CLI could be waiting …
> ✨ Better progress logging

- packages/env/src/environment.js
- packages/env/test/github.test.js
This will at least get the happy path of parallel builds going. We'll need an advanced doc to highlight the issues with this (`GITHUB_RUN_ID` is not unique on rebuilds, which will cause Percy to fail). Touches on #296, but doesn't completely solve it.
> ✨  Add basic parallel nonce support for GitHub actions

- packages/cli-command/src/command.js
- packages/cli-snapshot/src/commands/snapshot.js
- packages/cli-snapshot/src/config.js
- packages/cli-snapshot/test/snapshot.test.js
- packages/config/src/validate.js
- packages/config/test/index.test.js
- packages/core/src/config.js
This PR refactors and tweaks the `percy snapshot` command to be a little more friendly.
First, a page listing no longer needs to be a list of objects containing at least a `url` property. Now the file can contain just a list of URLs in the appropriate format:
```yaml
- https://example.com
- https://example.com/about
- https://example.com/contact
```
Second, the `--base-url` flag was made to work with page listings in addition to the existing static directory usage. Since usage differs between page listings and static directories however, some other small adjustments were necessary.
For static directories, the base URL should be the base **_PATHNAME_** that the site would be hosted at. Most sites are hosted at the domain root (`/`), however some sites might be hosted at other paths (e.g. …
> ✨ Allow snapshotting a list of pages to utilize the base-url flag

- packages/core/README.md
- packages/core/src/browser.js
- packages/core/src/config.js
- packages/core/src/page.js
- packages/core/src/percy.js
- packages/core/test/discovery.test.js
Sometimes, cookies sent via a `Cookie` header don't always seem to work (#374). While I couldn't exactly reproduce a scenario where the header wouldn't work, I thought it would be helpful to have a dedicated `cookies` option anyway. The dedicated option can help avoid confusion for people who are unfamiliar with the associated header, and also allow setting cookies for specific domains or paths.
The config schema was updated to allow a `discovery.cookies` option that can either be an object containing key-value pairs of cookies, or an array containing [cookie parameters](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-CookieParam) with `name`, `value`, and other cookie properties.
While it was straightforward to add cookies within page initialization, I discovered …
> ✨ Allow setting discovery browser cookies

- packages/env/src/utils.js
If you look at our CI logs, you'll see plenty of `fatal error` messages related to git. The root of the message is because the `checkout` step of our CI does a shallow (0 history) checkout of the repo. When the git command is run with the commit sha, it cannot find the associate commit object and logs this error. 
Similarly, if the CLI is run outside of a git repo, git errors are also logged.
Turns out, this is because `execSync` defaults stderr to `inherit` rather than `pipe` which is the default of stdout, stdin, and stdio for spawn functions.
This PR explicitly sets this stdio to ignore stderr, stdin, and pipe stdout.
No test here since the only thing we could write would be "is called with the right stdio options." Which doesn't feel like a useful test anyway since those options …
> 🐛 Ignore env git stderr logs

- packages/core/src/percy.js
- packages/core/src/utils.js
- packages/core/test/snapshot.test.js
Resource URLs should include the root origin, otherwise our infrastructure proxy fails to properly proxy the request over secure connections. This behavior is likely due to a default origin somewhere being http attempting to validate against https.
This PR takes advantage of `new URL(input, base)` behavior, where the origin of the second argument is used as the base of the input when the input is an absolute or relative pathname.
> 🐛 Fix percy-specific css resource url

- packages/core/src/discovery.js
- packages/core/test/discovery.test.js
In asset discovery when the cache is disabled, it doesn't matter if the `getResource` option returns an existing resource. The existing resource will always be overridden with new response. However, root resources aren't normally included with other resources. So when a root resource requests itself (such as a canonical link) and cache is disabled, a new resource is created for the root response (but `is-root` is not set since it happens during normal discovery). Later, when the root resource is added to the discovered resources, it ends up in the list of resources twice.
Fixing this is pretty straight forward. We just need to always skip capturing the root resource, even if the cache is disabled.
Fixes #388
> 🐛 Always ignore existing root resources during asset discovery

- packages/core/src/percy.js
- packages/core/test/snapshot.test.js
@chris-dura helped point out in #392 that additional snapshot options were being passed incorrectly to the `page.snapshot()` method.
The additional options (`opts`) should override parent options (`conf`). We also don't need to explicitly provide `execute` since it is included in `opts` and wasn't being extracted from the additional snapshot anyway.
> 🐛 Fix additional snapshot options

- packages/cli/index.js
Even though NPM/yarn checks on install, due to the number of warnings/errors in a given JS project, it's never noticed. We're going to hard error and exit on any unsupported versions of Node now to prevent support requests based on this.
> 🥅 Check version of Node, exit if not supported

- packages/core/src/network.js
- packages/core/src/percy.js
- packages/core/test/discovery.test.js
As described in #399, when requests will not be captured, they can clog up network idle and cause snapshots to take longer to process. However, if we were to untrack remote requests, as that issue suggests, pages might not yet be ready to snapshot when capturing the DOM ourselves since external resources are sometimes required by sites to load properly.
Instead, this PR adds a new feature to the network idle method to filter requests that are awaited on. This new filter can be used when not capturing our own DOM snapshot to only wait on requests from allowed hostnames.
I added a test for capturing lazy images as a precursor to a new test for not awaiting on remote resources (this test will timeout when failing). Lazy images are used in these tests because non-lazy images are normally …
> ✨ Do not wait for remote requests to idle during asset discovery

- karma.config.js
- packages/dom/src/serialize-frames.js
- packages/dom/test/serialize-frames.test.js
As per #396, when a same-origin frame is serialized, all of its content becomes relative to the frame parent, which can then result in invalid resource URLs. Like the issue suggests, we can transform the URLs within the frame document to be fully qualified URLs based on the frame document's URL.
During the recursive DOM serialization, we can provide a custom transform function to be applied to iframe documents after cloning but before the function returns a string. In this transformation we can then find all relevant elements to transform their respective URLs.
According to HTML 4/5 spec the `href`, `src`, `srcset`, `poster`, and `background` attributes are attributes that may contain URIs (and that we care about transforming). Most attributes' property counterparts are already resolved, …
> 🐛 Serialize iframe document URLs

- packages/client/src/request.js
- packages/client/test/proxy.test.js
With `new URL()`, the default port is never included in the resulting object, even when explicitly defined.
```js
new URL('http://localhost:80').port
// => ""
new URL('https://localhost:443').port
// => ""
```
In the `@percy/client` proxy, the proxy address' port is passed along to the `(net|tls).connect` method. With the above in mind, this results in an empty string being passed along. Since the `port` option is a required argument of the method, this causes connections to immediately close, showing only a vague error.
This PR adds a small `port` util which will return a default port if one isn't specified, port 443 for HTTPS requests or port 80 otherwise. This util is then used in the two places where a URL port is referenced.
Fixes #402
> 🐛 Fix default proxy port

- packages/config/src/defaults.js
- packages/config/src/load.js
- packages/config/src/migrate.js
- packages/config/src/normalize.js
- packages/config/src/utils.js
- packages/config/src/validate.js
- packages/config/test/index.test.js
- packages/core/src/config.js
While adding better validations for config options and per-snapshot validations, data must be validated against schemas other than the global config schema. To facilitate this, the validate util was refactored slightly. The merge util is also used within the core snapshot options config function to merge and validate provided options with config options and defaults while also handling deprecated options. Due to the merge util's limitation of only merging two objects at a time while mutating the first object, it had to be used several times in a row in order to merge all of the snapshot options together into a new object. Furthermore, it's options argument was limited in it's abilities and the merge function itself was centered around config normalization, so wasn't generic enough to use …
> ♻️ Refactor percy/config utils

- packages/core/src/browser.js
- packages/core/src/page.js
Sometimes, we get an occasional flakey CI failure due to missing branch coverage, which doesn't highlight which line number the coverage was missed for in the CI summary.
The reason that coverage is flakey but tests pass is likely due to a close enough assertion. For example, a test that asserts the page was closed might test for `/closed/` because sometimes the message is `Browser closed` instead of `Page closed` (both messages mean the page is closed, so the test is still accurate).
All page/browser errors are handled in one of two places, and the resulting handling and desired outcome is the same. There was already a coverage ignore statement on one handler, and another nested within the second handler. Both ignore statements were adjusted to reflect that they race with one another. …
> 🙈 Update coverage ignore statements for race conditions

- packages/core/README.md
- packages/core/src/config.js
- packages/core/src/index.js
- packages/core/src/percy.js
- packages/core/test/snapshot.test.js
While working on #305, the decision was made to have the config schema for snapshot options included in `@percy/core` since that is where the options are consumed. Initially however, core only registered the schema while the snapshot command used it to validate snapshot listing options.
With #406 refactoring the `merge` and `validate` utils, the `getSnapshotConfig` helper can now be refactored to utilize their new features to better merge and now validate options! This brings config validation to all of the SDKs as warnings logged whenever `percySnapshot` is called with unrecognized or invalid options.
Speaking of invalid options, this PR also adds more restrictions to existing config options:
- The `widths` and `minHeight` options have min and max values. These values are derived from …
> ✨ Add per-snapshot config validation!

- packages/cli-snapshot/src/commands/snapshot.js
- packages/cli-snapshot/src/config.js
- packages/cli-snapshot/src/hooks/init.js
- packages/cli-snapshot/test/snapshot.test.js
This resolves #305 and piggybacks off of #406 & #416 to validate page listings passed to the snapshot command. In addition to validations, page listing files can now contain a top-level `snapshots` key which references the list of snapshots. This enables YAML files to utilize [anchors, references, and extending](https://blog.daemonl.com/2016/02/yaml.html).
Tests were also reorganized a little and cleanup is done with the help of a rimraf transient dep.
> ✨ Validate snapshot command page listings

- packages/cli-snapshot/README.md
- packages/cli-snapshot/package.json
- packages/cli-snapshot/src/commands/snapshot.js
- packages/cli-snapshot/src/config.js
- packages/cli-snapshot/test/snapshot.test.js
- yarn.lock
This allows static snapshots to be configured with per-snapshot options!
``` yaml
static:
files: **/*.{html,htm}
overrides:
- files: /foo-bar.html
waitForSelector: .is-ready
execute: |
document.querySelector('.button').click()
```
I'm not too thrilled with the `overrides` name; could be `options`, `snapshotOptions`, `etc`?
> ✨ Add static snapshot overrides option

- packages/cli-upload/src/commands/upload.js
- packages/cli-upload/src/config.js
- packages/cli-upload/test/upload.test.js
This resolves #391 and utilizes core's queue class to parallelize the upload command. It adds a `upload.concurrency` option as well to allow control of the queue size. It also borrows a pattern from core by waiting on uploads at the "end" of the process and clearing the queue on error to allow the process to continue.
> ✨ Add queue concurrency to the upload command

- packages/cli-build/package.json
- packages/cli-command/package.json
- packages/cli-config/package.json
- packages/cli-exec/package.json
- packages/cli-snapshot/package.json
- packages/cli-upload/package.json
- packages/cli/package.json
- packages/client/package.json
- packages/config/package.json
- packages/core/package.json
- packages/sdk-utils/package.json
We should be lock stepping all our sub-packages since they're all released together. This also makes it possible to downgrade the CLI to a specific version
> ♻️ Lockstep sub-package versions

- packages/cli-command/test/command.test.js
- packages/cli-exec/src/hooks/init.js
- packages/cli-snapshot/src/commands/snapshot.js
- packages/cli-snapshot/src/config.js
- packages/cli-snapshot/src/hooks/init.js
- packages/cli-upload/src/hooks/init.js
- packages/config/src/validate.js
- packages/config/test/index.test.js
- packages/core/src/config.js
- packages/core/src/index.js
In tests, schemas are loaded where needed. In practice however, core schemas are not loaded in time for references in the snapshot schema. The answer is to register core schemas before they are needed, however by default this causes AJV to error about existing schema `$id`s when core get's around to registering schemas for itself.
The `addSchema` util was updated to replace existing `$id` schemas just as it already does for config file schemas. A test was added for this, but because the array handling was moved, coverage became low. Another test for an array of schemas was added to account for this missing coverage.
Since arrays of schemas are handled by our util now rather than forwarded directly onto AJV, a new pattern was adopted in the appropriate places. Where multiple schemas are …
> 🐛 Ensure core schemas are loaded before dependent snapshot schemas

- packages/cli-upload/src/commands/upload.js
- packages/cli-upload/src/config.js
- packages/cli-upload/src/resources.js
- packages/cli-upload/test/upload.test.js
This implements and resolves #412 with a new `--strip-extensions` flag and accompanying config file option.
The upload config options spreading was growing, so was adjusted to reference the config object rather than spread each individual config option.
The extensions are removed from file paths by parsing the path and rejoining without the extension. While doing this, I realized that the `name` parameter does not include parent directories and updated the resource helper accordingly.
The allowed file type regular expression was also updated since it now tests the file extension only and not the entire path.
> ✨ Add upload option to strip file extensions

- package.json
- packages/cli-build/package.json
- packages/cli-command/package.json
- packages/cli-config/package.json
- packages/cli-exec/package.json
- packages/cli-snapshot/package.json
- packages/cli-upload/package.json
- packages/cli/package.json
- packages/client/package.json
- packages/config/package.json
- packages/core/package.json
- packages/dom/package.json
- packages/env/package.json
- packages/logger/package.json
- packages/sdk-utils/package.json
Close #435
This change is created by the following Bash script:
```bash
#!/usr/bin/env bash
set -eu -o pipefail
files=$(git ls-files | grep package.json)
for file in $files; do
echo "Adding repository to ${file} ..."
dir=$(dirname $file)
if [[ $dir == "." ]]; then
npm pkg set repository.type="git" repository.url="https://github.com/percy/cli"
else
npm pkg set repository.type="git" repository.url="https://github.com/percy/cli" repository.directory="$dir" --workspace="$dir"
fi
done
```
(Note: `npm pkg` is available since [npm@7.20.0](https://github.com/npm/cli/releases/tag/v7.20.0))
Also, the changed `package.json` files can be verified by the following command:
```console
$ cat .npmpackagejsonlintrc.json
{
"rules": {
"require-repository": "error"
}
}
$ npx npm-package-json-lint .
```
See …
> 🔨 Add `repository` field to `package.json` files

- .github/.cache-key
- packages/core/src/install.js
- scripts/chromium-revision
This rolls the asset discovery browser used by `@percy/core` forward to Chrome 92 (from 87)
This PR was originally for Chrome 91, but after a week of trying to debug/diagnose Windows issues with asset discovery in tests (and real life, likely), it made sense to move on and try a newer version. Chrome 92 passed all our tests on the first go, so we're going to roll forward with 92.
> ✨ Roll asset discovery browser to Chrome 92

- packages/core/src/page.js
Unfortunately, while #408 appeared to address a race between browser and page error handling, there existed other codepaths that could also race in the same way for the same reason.
For this codepath, the code was formatted in a way where we were only ignoring line coverage. The function though, is still created and in certain circumstances may not be called (which was the original goal of this ignore statement).
This PR updates the formatting and ignore statement so the entire handler is ignored. I found this "missing" coverage by studying the coverage output and figuring out which functions were being hit the least. The crash handler was only hit once, but we explicitly test for it. However, I noticed the ignore statement there and also in the `close` method in which it was ignoring. …
> 🙈 Fix coverage ignore statement for racey errors

- packages/cli-snapshot/README.md
- packages/cli-snapshot/package.json
- packages/cli-snapshot/src/commands/snapshot.js
- packages/cli-snapshot/src/config.js
- packages/cli-snapshot/test/snapshot.test.js
- packages/config/src/normalize.js
- packages/config/test/index.test.js
- yarn.lock
This adds two new options for static snapshots and refactors small parts of the snapshot command.
Logic that differed between static and non-static usages were moved into their respective implementation specific methods. This includes `base-url` error handling and default/normalized page options. Although the latter is shared, how the server address and non-static `base-url` is determined is specific to each implementation. Tests were also refactored a bit so suite hooks run for each test, and a couple other small test changes were made as well.
The `clean-urls` option is passed along to the static server handler directly, while the `rewrites` option is concatenated to any `base-url` rewrite. The `rewrites` are then also used in conjunction with `overrides` to generate a default page URL …
> ✨ Add static snapshot clean-urls and rewrites options

- .github/release-drafter.yml
- .github/workflows/stale.yml
This action will help us keep on top of our issues and PRs. After 14 days of no activity there will be a warning comment made. If no activity is taken from there, the issue or PR will be closed 14 days later (28 total days of no activity). The action will run once a week on Tuesdays at 2pm CST.
> 🧹 Add stale issues/PRs action

- packages/cli-config/src/commands/config/migrate.js
- packages/cli-snapshot/src/config.js
- packages/config/src/load.js
- packages/config/src/migrate.js
- packages/config/src/normalize.js
- packages/config/src/utils.js
- packages/config/src/validate.js
- packages/config/test/index.test.js
- packages/core/src/config.js
- packages/core/src/percy.js
- packages/core/src/server.js
- packages/core/test/percy.test.js
- packages/core/test/server.test.js
- packages/core/test/snapshot.test.js
With #447, the new `static.rewrites` config file option was added to a config module constant that determines which object properties are normalized and which aren't. Before that PR, the constant was initially created to prevent normalizing `discovery.request-headers` options, and subsequently later `discovery.cookies` options.
This was all easy to do as the changes came up since the aforementioned options were defined by other packages within this repo. However, outside of this repo where config schemas can still be defined, there is no such mechanism for disabling normalization of a property. In order to do so, a dedicated PR must be opened on this repo to add the desired properties to the constant.
Instead, with this PR, normalization can be disabled for a property by its own schema. …
> ✨ Normalize config with schemas

- packages/core/src/percy.js
- packages/core/test/discovery.test.js
During the recent discovery/snapshot refactors, the `Page` class was updated to default `enableJavaScript` to `true` for other packages to borrow a page without explicitly enabling it. However, since `enableJavaScript` did not have a default configuration value for dom snapshots in the `Percy` class, that resulted in all snapshots defaulting to have javascript enabled during asset discovery (this does not affect the API default).
I also noticed that for snapshot captures, JavaScript is always enabled, even if the config option is `false`.
I updated this line to always prefer the `enableJavaScript` option and default based on the presence of `domSnapshot`. When there is no dom provided, the default should be `true`, otherwise it should be `false`. I also added a test so this can be caught …
> 🐛 Fix enableJavaScript default for snapshot discovery

- packages/cli-exec/src/hooks/init.js
- packages/config/src/migrate.js
- packages/config/src/normalize.js
- packages/config/test/index.test.js
- packages/core/src/config.js
- packages/core/src/index.js
- packages/core/test/unit/config.test.js
With #450, the migrate function was updated to be able to migrate specific schemas. We can now utilize that new feature to register a snapshot config migration for deprecated options. These deprecations previously lived within a merge callback.
The migrate function was updated again in this PR to accept multiple migration at once similar to how we can register multiple schemas at once. The forced version was also moved into a default migration; and to ensure it always runs last, migrations are now registered in reverse order, so they run last-in-first-out.
> ✨ Allow registering multiple config migrations at a time

- packages/cli-snapshot/src/commands/snapshot.js
- packages/cli-snapshot/src/utils.js
This not only cleans up the main snapshot command class and makes it easier to distinguish between different functionalities, but it also allows us to use these utils for other purposes, such as for static site generator SDKs (currently gatsby, could be more in the future).
For the most part, this PR just moves some stuff around. The `withDefaults` and `serve` methods are now utils, and the path-page mapping was moved into it's own util. Smaller changes were made to replace `this` references with config arguments.
> ✨ Refactor static snapshot logic into utils

- packages/core/src/install.js
- packages/core/test/unit/install.test.js
- scripts/chromium-revision
For a while, Chromium for Mac was only built on x64 architecture. With the advent of new M1 arm Macs, it wasn't clear if the Percy CLI even worked on these new macs since we rely on Chromium for asset discovery. I looked back into the Google storage APIs and found that there were recent additions that added Mac arm support. This PR adds the appropriate changes so our install script will download the correct version of Chromium when run on arm based Macs.
> ✨ Install the correct Chromium binary for arm Macs

- packages/core/src/browser.js
- packages/core/src/network.js
- packages/core/src/page.js
- packages/core/src/percy.js
- packages/core/test/discovery.test.js
This PR addresses a couple of networking issues in asset discovery.
Foremost, while debugging a very minimal reproduction of asset discovery hanging, it was very helpful to know which requests were causing the issue. This resulted in an improved network timeout log, which includes a list of the offending request URLs in debug logs.
With the improved logs, it was easy to see that there was an issue with requests for some frame documents. With some additional, very noisy, event logs (not included), it revealed that once the document's response was received, the subsequent request finished events were never observed.
This prompted an investigation into how events are handled with embedded documents, and it was then discovered that Chromium's …
> 🐛 Fix situations where asset discovery might hang

- packages/core/src/network.js
- packages/core/src/page.js
- packages/core/test/discovery.test.js
Thanks to #490, it now makes it possible to properly capture resources from isolated pages. However, during the network idle check, only the top-level network method is used which only references its own requests. This PR adds tracking isolated pages to the parent page to create a inverse relationship. And also adds a new network method to retrieve all nested page requests during the idle check. These changes make it so network idle will check for nested requests in addition to its own requests.
While here, I also came across a familiar race condition in the page constructor as a result of the page closing during an async call within the constructor. This same race condition exists in the network constructor, however with a check to prevent intentional page closed errors from bubbling. …
> 🐛 Wait for isolated networks to idle

- packages/cli-command/src/command.js
- packages/cli-command/src/flags.js
- packages/cli-command/test/command.test.js
- packages/cli-exec/README.md
- packages/cli-snapshot/README.md
- packages/core/README.md
- packages/core/src/percy.js
- packages/core/test/percy.test.js
- packages/logger/src/index.js
- packages/logger/test/logger.test.js
Asset discovery issues are typically debugged with the `--verbose` flag, or by setting the environment variable `PERCY_LOGLEVEL=debug`. While this option prints detailed logs throughout the toolchain, including asset discovery, it only does just that — prints detailed logs. However, when debugging asset discovery issues, the constant uploading of any snapshots results in a hit to screenshot usage. It would be beneficial while debugging asset discovery issues to simply not send any snapshots at all, or not even create a build to begin with.
This PR introduces a `--debug` flag, which not only enables debug logs just like the `--verbose` flag, but additionally disables snapshot uploads via a new core `skipUploads` option. This option mirrors the existing (but unused) `deferUploads` option. …
> ✨ Add --debug discovery flag

- packages/config/src/utils.js
- packages/config/test/index.test.js
This PR fixes a couple small bugs I found in `@percy/config`:
- When validating arrays as the root subject, the resulting message would contain a path like `0].example`. This was fixed by only stripping leading periods from joined paths rather that stripping the first character blindly.
- When normalizing objects that are not plain objects or arrays (Date, RegExp, etc), the object was inadvertently removed from the result. This was fixed by explicitly testing for the correct type of objects we're looking for. The util was named `hasKeys` in case we ever need to account for other types of iterable objects (but not all of them).
> 🐛 Fix small config util bugs

- packages/config/src/migrate.js
- packages/config/src/utils.js
- packages/config/test/index.test.js
- packages/core/src/config.js
- packages/core/test/snapshot.test.js
- packages/core/test/unit/config.test.js
We currently only have a single place where config migrations log a few deprecation warnings, and that is in `@percy/core`. We also had/have deprecations in the Storybook SDK, although that SDK recently left beta and so the deprecations are/will be removed. In the future, other config deprecations might come up, and so it would be helpful to consolidate how deprecations are handled into a single migrate util passed along just like the other current migrate utils.
This PR also updates `@percy/core` migration deprecations to use the new util.
Depends on #493 as these changes are how I discovered those bugs.
> ✨ Add deprecate config migrate util

- packages/config/src/migrate.js
- packages/config/test/index.test.js
- packages/core/src/config.js
- packages/core/test/unit/config.test.js
The option to deprecate `until: version` reads more accurately than `in: version` and reflects that the user has _until_ that version to move away from the deprecation.
> ♻ Small revision to the deprecate migrate util api

- packages/cli-command/src/command.js
- packages/cli-command/test/command.test.js
The `initialOverrides` value of the shared CLI `#percyrc()` method does not work as intended. Flags always override the initial overrides, even when the flag is undefined, resulting in desired values being removed from the resulting config object.
This PR fixes the issue by aborting the override if the flag is null or undefined. I also borrowed the `set` util from `@percy/config` to set the overridden flag using a much more tested method. An existing test was also updated to remove unnecessary set up.
> 🐛 Do not replace initial overrides with empty flags

- packages/core/src/percy.js
- packages/core/test/discovery.test.js
Thanks to @cancan101, it was pointed out that the browser may cancel responsive image requests between resizes. While we have a test for this, the test wasn't quite comprehensive enough. Adding a third width to the test reveals that intermediary responsive asset requests between the first and the last are indeed cancelled because the viewport is resized too quickly. The first asset in this test likely only succeeds due to page navigation waiting for the `load` event.
This PR adjusts the test so it accurately fails, then duplicates discovery's idle check before resizing. Unfortunately, this fix has a drawback that causes snapshots to take slightly longer than they used to, by a magnitude of `networkIdleTimeout * (widths.length - 1)`. So a network idle timeout of `100ms` across 3 widths …
> 🐛 Wait for network idle for responsive asset discovery

- packages/cli-snapshot/src/config.js
This PR adds a safety check to the migrate function to avoid errors when there are no `static` config options (which usually happens when using any other command).
More evidence that a root-level integration test suite is needed. This error only happens with other commands but each command is tested in isolation (mostly).
> 🐛 Fix reference error when static config options are not defined

- packages/core/src/config.js
- packages/core/src/page.js
- packages/core/src/percy.js
- packages/core/test/discovery.test.js
- packages/core/test/snapshot.test.js
This PR adds the ability to specify additional execute options to run scripts at specific states during the snapshot process. By default, the original `execute` function would only be evaluated right before a snapshot is taken. Now, there are additional options for `afterNavigation`, `beforeResize`, `afterResize`, and `beforeSnapshot`. If `execute` is provided as a function without these additional options, it is treated as a shorthand for `execute.beforeSnapshot`.
Thanks to @cancan101 for the idea! With these new options, it makes it easier for people to handle lazy-loaded images before the page gets resized. Closes #513
> ✨ Accept additional snapshot execute options for various states 

- packages/cli-snapshot/src/commands/snapshot.js
- packages/cli-snapshot/src/config.js
- packages/cli-snapshot/src/utils.js
- packages/cli-snapshot/test/sitemap.test.js
This makes it possible to use `percy snapshot <sitemap-url>` to take snapshots of all of the URLs listed by a sitemap.
The changes in the PR leverage the existing `mapStaticSnapshots` util, thus allowing `include`, `exclude`, and `overrides`. Technically, this util also allows a couple of other static options, however those options (such as rewrites and base-url) are not necessary as URLs within a sitemap are typically canonical URLs.
If a fetched sitemap is not an XML document, an error will be thrown. In the future, it's possible this can be relaxed a little since our regexp parser doesn't necessarily need valid XML to work (it simply matches URLs between XML `<loc>` tags).
I also discovered that some sitemaps list a URL twice, with and without a trailing forward slash (`/`). This …
> ✨ Accept sitemaps with the snapshot command!

- packages/cli-snapshot/README.md
- packages/cli-snapshot/src/commands/snapshot.js
This adds forgotten docs for the new `percy snapshot <sitemap-url>` feature from #516.
> 📝 Add docs for snapshotting sitemaps

- packages/cli-snapshot/src/commands/snapshot.js
- packages/cli-snapshot/test/sitemap.test.js
This fixes a bug in the sitemap URL filtering logic where if a URL ends in a forward slash and does not exist in the sitemap without one, it will be removed from the sitemap.
> 🐛 Fix sitemap unique URL filtering bug

- packages/core/src/page.js
- packages/core/test/snapshot.test.js
Thanks to @cancan101 for testing out the new `execute` features from #514 and finding a bug. When `execute` is provided without a `beforeSnapshot` option, the entire `execute` object is passed on to the evaluate function, which creates an unserializable function as a result.
Rather than coalesce the `execute` option, we can typecheck if it is a function and fallback to `execute?.beforeSnapshot`.
> 🐛 Fix bug when providing execute without before snapshot

- packages/cli-build/src/commands/build/finalize.js
- packages/cli-build/src/commands/build/wait.js
- packages/cli-snapshot/src/commands/snapshot.js
- packages/cli-upload/src/commands/upload.js
- packages/client/src/client.js
- packages/client/test/client.test.js
- packages/core/src/percy.js
- packages/core/test/percy.test.js
- packages/core/test/snapshot.test.js
This implements a warning log if the SDK sends a snapshot without any user agent info (`environmentInfo` & `clientInfo`). Closes #455 
Before releasing this, we will need to update the Storybook SDK
> 🔊 Add log to warn when SDK user agent is missing

- packages/core/src/browser.js
- packages/core/src/network.js
- packages/core/src/page.js
- packages/core/src/session.js
- packages/core/test/discovery.test.js
- packages/core/test/snapshot.test.js
With #530, it was found that worker requests cause the network to hang. The approach in that PR was to ignore requests from workers. After new tests failed on Windows enough times, it was discovered that the test itself was a bit faulty. Once it was made deterministic via the worker updating DOM state, it consistently failed no matter the platform.
After a day of debugging, I discovered that workers inherit the `Fetch` domain of their parent session, but not the `Network` domain. Since both domains need to be enabled in order for request interception to work, requests within workers were being paused but never continued. In order to attempt to disable the inherited `Fetch` domain, we would have to alter how pages are initialized since workers do not have many of the domains that the page …
> ♻️ Refactor page, network, and session handling

- packages/core/src/discovery.js
- packages/core/src/network.js
- packages/core/src/percy.js
- packages/core/test/discovery.test.js
Currently, when using the snapshot command (or any SDK that does not provide their own DOM snapshots), JavaScript is enabled for the local page context during capture to ensure the page is loaded properly, but it is still disabled by default when the snapshot is sent to Percy for screenshot stability.
Because it is enabled during asset discovery, we are capturing JavaScript assets and XHR requests that will never be used in Percy's infrastructure due to JS being disabled there. This PR adds tracking the paused request's resource type and a condition around that type during processing that will only allow specific resources to be captured when JS is disabled. When JS is enabled, all resources will be captured as before (provided none of the other non-capturing conditions are met).
While …
> 🐛 Do not capture scripts or XHR requests when JS is not enabled

- packages/core/src/install.js
- packages/core/test/unit/install.test.js
Two small logging-related bug fixes when the browser is installed:
1. The calculated seconds shown was for the entire eta estimate, including minutes. This meant that if the eta was 4 minutes, the eta shown would be `04:240`. 
This was fixed by adding the modulus operator (`%`) to get the remaining seconds.
2. The calculated minutes shown was accidentally rounded when using `.toFixed()`. This is the expected behavior of this method, but not what we want when formatting minutes. 
This was fixed by using `.toString().split('.')[0]` in its place, which does not round.
I modified an existing test to verify the formatting, which helped to remove a previously ignored line of coverage.
> 🐛 Fix the eta shown when installing the browser

- packages/core/src/snapshot.js
- packages/core/test/discovery.test.js
It appears `networkIdleTimeout` is currently not being set from config or the CLI. This PR ensures the network idle timeout gets correctly set. 
Will fix #643.
> 🐛 Ensure `networkIdleTimeout` is correctly passed and set

- packages/core/src/page.js
- packages/core/src/snapshot.js
- packages/core/test/snapshot.test.js
Fixes #600 (`additionalSnapshots.execute` not working with a string value). The config schema for additional snapshots specifically allows strings, functions, or arrays of strings and/or functions. This PR inverts the previous check to only use `execute.beforeSnapshot` if the `execute` option is an object but not an array.
This also fixes an issue where `execute` could be incorrectly inherited by additional snapshots and run multiple times.
> 🐛 Fix additional snapshots executing string functions

- .eslintrc
- packages/cli-exec/src/commands/exec/start.js
- packages/cli-exec/test/start.test.js
- packages/core/src/browser.js
- packages/core/src/page.js
- packages/core/src/percy.js
- packages/core/src/queue.js
- packages/core/src/server.js
- packages/core/src/utils.js
- packages/core/test/percy.test.js
- packages/core/test/snapshot.test.js
- packages/core/test/unit/queue.test.js
Currently, tasks within the internal queue, including snapshots, are cancelable. This is done by utilizing generators as tasks. This PR takes that concept and uses it to make other core methods cancelable as well. Having these methods be cancelable will allow better handling of process termination in the CLI rather than relying on promises to completely settle.
While implementing this, I discovered that I had many hanging Chromium processes after several tests. This prompted me to tighten up some browser internals to alleviate it. Also while implementing this, the upload queue's concurrency was fixed to mirror the snapshot queue, and the `setConfig` method was updated to allow configuring the discovery concurrency after percy has already started.
To make certain core methods cancelable, …
> ✨Cancelable @percy/core methods

- packages/client/src/utils.js
- packages/client/test/unit/request.test.js
Given zero retries, the retry util would always retry at leasty once. Given any number of retries, the retry util would count the first try against remaining retries. For example, a failed request without retries would always retry at least once, and a failed request with 5 retries would fail once, then retry 4 times.
When properly counting retries, the first try is not counted against retries, and similarly will not retry when given zero retries.
> 🐛 Fix @percy/client retries

- packages/sdk-utils/test/server.js
While running tests for the entire repo, I noticed that tests for `@percy/sdk-utils` would occasionally log an error but not fail. After some brief digging, I found it was because the data being asserted against is a buffer, not a string like the comparison is expecting. This PR adds `.toString()` to this check to ensure that it's actually comparing against a string.
> ✅ Fix sdk-utils test server shutdown

- .gitignore
- packages/cli/bin/run
- packages/cli/src/index.js
- packages/cli/src/update.js
- packages/cli/test/commands.test.js
- packages/cli/test/helpers.js
- packages/cli/test/update.test.js
This PR adds an update notice when it detects a newer version of the CLI is available.
Before parsing command-line arguments, releases are requested from GitHub's API and compared against the currently installed CLI's version. 
Releases are cached for 3 days before being re-requested, with fallbacks in place so the check still happens if there are errors when reading or writing to the cache file.
The `mockfs` test helper was updated to support a better `spyOn` syntax for `memfs.fs` methods and also automatically mock the current working directory.
> ✨ Add @percy/cli update notice

- packages/core/src/utils.js
This fixes the `waitFor` util in `@percy/core` to properly return the tail call. Without tail call optimization, error stacks that bubble from within the util can grow exponentially.
> 🐛 Fix tail call recursion in core util

- packages/cli-command/src/legacy.js
Some legacy commands do not define their own `finally` method. If they extend from a class that also does not have a `finally` method (like if they accidentally extend from the `command` function), process termination throws an error.
> 🐛 Fix legacy process termination when missing instance method

- package.json
- packages/client/package.json
- packages/config/package.json
- packages/core/package.json
- packages/dom/package.json
- packages/env/package.json
- packages/logger/package.json
- packages/sdk-utils/package.json
- yarn.lock
With recent refactoring of the various `@percy/cli*` packages, their respective `package.json` files were cleaned up slightly. This PR cleans up other package's `package.json` files the same way those refactors did for their packages.
Mainly, repository and publish information were moved to the top of the files with other meta info.
For the top-level `package.json` file, the `@oclif/dev-cli` dependency was removed. The top-level `test` script was also adjusted to allow failures since it is only used locally, whereas in CI dedicated parallel jobs are run for each package.
> 🧹 Clean up package.json files

- packages/cli/bin/run
It looks like `npx` is doing weird caching of `@percy/cli`, so when we do `import('@percy/cli')`, it's possible for the import to be an old cached (incorrect) version of the CLI.
To avoid this, we're going to require the root CLI package so it's _always_ getting the same package & ensure the package matches the invoking bin
> 🐛 Import local `@percy/cli` to avoid caching/multiple CLI issues

- packages/core/src/utils.js
The check within the `waitFor` util was originally created as a recursive function. With recent changes, the util was converted to make use of the cancelability of generators. However, generators cannot be tail-call optimized like the previous implementation was. This is due to technical reasons within V8 around the nature of how generator's `next()` function handles script evaluation.
Because the `waitFor` util polls and may run for a long time, the lack of tail-call optimization caused the call stack to continuously grow the longer the util took to resolve. Eventually this could/will result in call stack errors (#735).
This PR refactors the generator within the util to use a `while (true)` loop rather than a recursive `yield*`. The infinite loop is broken if the `predicate` passes at …
> 🐛 Avoid recursion in generators due to no tail-call optimizations

- packages/cli/bin/run
Currently the `bin/run` file uses an ESM dynamic import. This wasn't something intended to ship _yet_ (especially since that file isn't touched by babel to transpile). Very soon we'll be going all in on ESM (which will require node 12.22+), but it shouldn't have slipped into the past two releases. This only impacts folks running a very old version of Node.
> 🐛 Update `bin/run` to not use an esm dynamic import

- packages/client/src/client.js
- packages/client/src/request.js
- packages/core/src/percy.js
The client request util is used in various places internally. This PR adds a small feature to automatically stringify json bodies and add the appropriate `application/json` content-type header. 
One planned future use of this feature is within our own tests. As such, response headers were also added to request errors (along with renaming the error response status to match the response property name).
> ✨ Automatically handle json bodies in client request util

- packages/cli-exec/src/common.js
- packages/cli-exec/src/exec.js
- packages/cli-exec/test/exec.test.js
- packages/cli-exec/test/ping.test.js
- packages/cli-exec/test/start.test.js
- packages/cli-exec/test/stop.test.js
After CLI commands were migrated to the new `cli-command` framework, the `cli-exec` command's `--port` flag was inadvertently disconnected from where it was previously passed in. With the new framework, all that's needed is an extra property to appropriately set this option.
This PR also fixes env assignments for currently relevant vars. This shouldn't be an issue in practice, but was causing tests to pollute each other.
Will fix #786
> 🐛 Add percy config mapping for cli-exec port flag

- packages/core/src/snapshot.js
- packages/core/test/snapshot.test.js
Currently, there is logic to produce a hard error when widths are missing from a snapshot. In reality, when widths are missing from a snapshot (even after invalid widths are scrubbed), the empty array is removed and the default Percy config widths are used. If the user provides empty config widths, they are also removed and the default ends up being used.
Having a hard error on missing widths also makes it difficult to reason about snapshot option overrides with upcoming features where options may or may not apply to a provided set of snapshots. This also raises the question as to why don't we produce hard errors for any other invalid options? Historically there has only ever been a hard error for missing snapshot URLs and widths.
This PR removes the hard error on missing widths while …
> ✨ Use default widths instead of throwing an error when missing

- packages/core/src/browser.js
Small housekeeping task I noticed and changed while working on other things. The default browser launch timeout is in an obscure place and as such requires passing around the custom option. Moving it to be next to other defaults allows for some cleaner code in this file.
> ♻️ Move browser timeout default to other launch option defaults

- packages/core/src/api.js
- packages/core/src/percy.js
- packages/core/src/queue.js
- packages/core/test/api.test.js
- packages/core/test/percy.test.js
- packages/core/test/snapshot.test.js
- packages/sdk-utils/src/post-snapshot.js
- packages/sdk-utils/test/helpers.js
- packages/sdk-utils/test/index.test.js
- packages/sdk-utils/test/server.js
When a build fails, the error is logged and the internal queues closed. When attempting to push or upload new snapshots, the queue throws a `Closed` error. The `sdk-utils` package checks if any API error have the message `Closed` to disable the local SDK. These `Closed` errors can occasionally still show up in the logged output which is confusing without any other context (context is usually further up in the logs anyway).
This PR updates this handling to better recommunicate the original error. When builds fail, the reason is cached so other methods can rethrow it rather than let the closed error bubble. Our tests no longer exercised the closed error, so it was made to silently fail for race condition protection. The CLI API was updated to include build details with errors, and the …
> ♻️ Improve build failure handling

- .eslintrc
- packages/cli-snapshot/src/config.js
- packages/cli-snapshot/src/snapshot.js
- packages/core/README.md
- packages/core/package.json
- packages/core/src/api.js
- packages/core/src/config.js
- packages/core/src/percy.js
- packages/core/src/snapshot.js
- packages/core/test/discovery.test.js
- packages/core/test/percy.test.js
- packages/core/test/snapshot-multiple.test.js
- packages/core/test/snapshot.test.js
- yarn.lock
This PR makes use of the new static server capabilities within `@percy/core` (#781) and the updated config schema from `@percy/config` (#804) to allow the `snapshot()` method to accept several alternate syntaxes for taking snapshots.
The updated config work is necessary to allow validating options against several related schemas which all share commonly used properties. Before, these properties would need to be repeated for each schema. With the updated schema spec, these schemas can inherit from one another and better reference each other within nested properties.
The new internal static server is started and stopped around a group of snapshots when providing specific snapshot server options. This better couples static servers to core's own internals which will help prevent issues where …
> ✨ Accept alternate core snapshot syntaxes

- packages/core/src/api.js
- packages/core/src/percy.js
- packages/core/src/snapshot.js
- packages/core/test/percy.test.js
- packages/core/test/snapshot-multiple.test.js
Removing components of `@percy/cli-snapshot` and replacing them with the new `@percy/core` snapshot syntaxes revealed a couple of small gaps in implementation details.
- Static server snapshots, when missing a specific list of snapshot, will fallback to the sitemap of the static server, however it is currently missing any provided `baseUrl`. This is fixed by joining the `baseUrl` with `path.posix.join`.
- If a glob pattern for the new `include`/`exclude` options does not start with a leading slash, it has erratic matching behavior. This is made more predictable by only matching on the path basename when missing a leading slash.
- With default options, a build will be created on start and finalized on stop, even if a sitemap, static server, or invalid list of snapshot results in no …
> 🐛 Fix core snapshot method compatibility with cli-snapshot command

- packages/cli-command/src/flags.js
- packages/cli-command/test/flags.test.js
- packages/cli-exec/README.md
- packages/cli-snapshot/README.md
- packages/core/README.md
- packages/core/src/config.js
- packages/core/src/discovery.js
- packages/core/src/snapshot.js
- packages/core/test/discovery.test.js
There are many cases where asset discovery can be hung up by remote assets that will never be captured. Most common issues are ad tracking requests or analytics requests. We can't wholesale exclude requests from asset discovery though, since it's possible for remote assets to request local assets (or assets that _are_ included in `allowedHostnames`). 
In order to make asset discovery more stable for customers, we are introducing the ability for them to specify hostnames which will be fast failed and aborted in asset discovery. This makes it so ad trackers or analytic trackers won't hang up or timeout asset discovery. 
Will close #773
> ✨ Introduce the ability to abort requests from specificed hostnames (`disallowedHostnames`)

- packages/sdk-utils/src/index.js
- packages/sdk-utils/src/percy-idle.js
- packages/sdk-utils/test/index.test.js
- packages/sdk-utils/test/server.js
When requesting the `/percy/idle` endpoint, if queued snapshots take longer to idle than the request timeout, the request will throw an error. This new `@percy/sdk-utils` helper will recursively call itself when the request times out, resulting in the ability to await on long running idle requests.
There is no logic for aborting the idle wait since the server should always eventually respond with a success or error. Even if the server hangs, killing it will result in a connection refused/disconnect error rather than a timeout. This new helper will always return true when idle, or false when a non-timeout error occurs (which will be logged by the CLI).
> ✨ Add sdk-utils waitForPercyIdle helper

- packages/core/src/server.js
- packages/core/test/snapshot-multiple.test.js
Performing this check when starting the static server will prevent us and other SDKs from having to do this check before creating a server at all. Without this error, all URLs will simply 404 since the files would not exist at the configured location.
> ✨ Throw an error when a static server directory does not exist

- packages/cli-exec/src/exec.js
- packages/cli-exec/src/start.js
- packages/cli-snapshot/src/snapshot.js
- packages/cli-upload/src/upload.js
- packages/core/src/percy.js
- packages/core/src/snapshot.js
- packages/core/test/percy.test.js
- packages/core/test/snapshot-multiple.test.js
- packages/core/test/snapshot.test.js
Amongst the new alternate snapshot syntaxes, the sitemap and serve options should be cancelable. Both should be cancelable either during URL gathering, or during snapshotting itself. Since all snapshots are queued immediately, relevant cancel code was moved into a dedicated method that is called for each snapshot when canceled.
The snapshot method is meant to be useable asynchronously. When providing missing or invalid snapshot URLs, it will throw immediately. Also calling the method without awaiting on it will queue snapshots regardless. With the current approach to cancelable methods, the `generatePromise` helper returns a promise-like generator that must be await on or yielded to in order to run. This would prevent synchronous snapshots from working as they would not automatically run. …
> ✨ Allow alternate snapshot syntaxes to be cancelable

- packages/core/src/snapshot.js
- packages/core/test/snapshot-multiple.test.js
A small improvement to the new snapshot syntaxes: functional snapshot gathering.
When using a syntax with the `snapshots: []` option, you can now provide a function to return a list of snapshots. This function will receive the `baseUrl` as its only argument. With the `serve` syntax, the `baseUrl` includes the server address allowing this function to scrape snapshots from alternate sources other than a sitemap.
For example, the Storybook SDK can collect story snapshots using this function. Similarly, if other component libraries allow access to an API which returns snapshots, this new option makes it extremely simple to integrate with Percy.
> ✨ Allow a function to gather snapshots using alternate syntaxes

- packages/dom/src/prepare-dom.js
- packages/dom/src/serialize-cssom.js
- packages/dom/test/serialize-css.test.js
- yarn.lock
Currently when we serialize in memory CSS (CSSOM) we only append the serialized styles to the bottom the documents `<head>`. This can cause issues with the ordering of the CSS. In order to fix this we should append the serialized styles _right after_ the CSSOM's `<style>` tag.
> 🐛 Insert serialized CSSOM `style` tag after CSSOM `ownerNode`

- packages/core/src/snapshot.js
- packages/core/test/snapshot.test.js
The queue mapping was not using the normalized URL for the root resource. This meant if the URL included a hash or just a port it would send the same normalized URL twice (which the API will reject). 
Will fix #641
> 🐛 Fix duplicate resource URL issues with `snapshot` method

- packages/cli-command/src/command.js
- packages/cli-command/src/parse.js
- packages/cli-command/test/command.test.js
- packages/cli/src/commands.js
- packages/cli/test/commands.test.js
A very small feature that saves a few lines of code now, but will save more lines of code in the future.
Currently, client and environment information is expected to be provided directly to core from the SDK. The vast majority of SDKs simply use information gathered from `package.json` files.
When automatically loading CLI based SDKs, we already have access to these package.json files. By setting a package information property on the autoloaded SDK command, we can then utilize that to automatically include client information when creating a core percy instance.
With this change, CLI based SDKs will no longer need to provided their own package.json based client information as it will already be available. This only leaves environment information — and since our CLI SDKs are loaded in the …
> ✨ Automatically include package information with CLI commands

- packages/dom/src/serialize-video.js
- packages/dom/test/serialize-videos.test.js
Sometimes it's not possible to serialize videos into poster due to security (`Tainted canvases may not be exported.`). Wrapping the `serializeVideos` function call in a try/catch will allow the DOM serialization to continue.
Will close #845
> 🐛 Wrap `serializeVideos` in try/catch to catch security errors

- packages/core/src/config.js
- packages/core/test/snapshot.test.js
When validating options against schemas, `allOf`, `anyOf`, and `oneOf`, errors are surpressed since they are confusing and the real error will typically bubble from one of the nested schemas. However, if those nested schemas are simple primative types, there is no additional error. And without an error the validation logic does not scrub the option.
This change fixes the issue by adding explicit errors for two of these schemas. In addition, the execute option was relocated so additional snapshots are not allowed to use an object (only a single execute function is allowed for additional snapshots).
Ideally, an error should only be suppressed if a nested error did (or will) bubble. If a would-be-suppressed error would be the only error, it should never be suppressed. Even if the resulting …
> 🐛 Fix supressed validation error causing options to not be scrubbed

- packages/cli-build/package.json
- packages/cli-command/package.json
- packages/cli-config/package.json
- packages/cli-exec/package.json
- packages/cli-snapshot/package.json
- packages/cli-upload/package.json
- packages/cli/package.json
- packages/client/package.json
- packages/config/package.json
- packages/core/package.json
- packages/env/package.json
- packages/logger/package.json
- packages/sdk-utils/package.json
The 1.0.0 release is botched because paths with leading dots cause yarn and npm to not properly package files. 🙃
> 🐛 Remove relative path from package files

- packages/config/test/helpers.js
- packages/core/package.json
According to core's `exports`, packages should be able to access `test/helpers` however the `index.js` file is not included in the packaged files. This PR fixes this by including all test helpers in the packaged files.
Additionally, this PR adds a small feature to the filesystem test helper to allow tests access to the bypass list.
> ✅ Include all core test helpers in packaged files

- packages/cli-command/package.json
- packages/config/package.json
- packages/env/package.json
Like #862, except I audited all package.json files. If a file is available in the `exports` field, it should also be included in the packaged files.
> 🐛 Audit package file exports

- .gitignore
- package.json
- packages/cli/test/commands.test.js
- packages/cli/test/helpers.js
- packages/cli/test/update.test.js
- packages/config/package.json
- packages/config/test/helpers.js
- packages/config/test/index.test.js
- packages/core/package.json
- packages/core/test/helpers/index.js
- packages/core/test/helpers/server.js
- packages/core/test/unit/install.test.js
- packages/core/test/unit/server.test.js
- packages/logger/test/helpers.js
- packages/sdk-utils/test/server.js
Besides misspelling a file in the last PR, we've been running into issue with package manager's `pack` output. This PR fixes the misspelling and adds a command to aid in packing up unreleased packages for testing.
This PR also changes config test helpers to lazily import their required deps. This makes it so packages can import these helpers without installing those deps. They will only need to be installed if one of the helpers that requires it is used.
Along with this import change, core exports were updated to allow import `test/helpers/server` directly rather than through the main `test/helpers` entry. This makes it so the sdk-utils test helper does not end up incidentally importing config and client helpers when it doesn't need them.
> ✅ More test adjustments

- packages/config/src/validate.js
- packages/core/src/snapshot.js
- packages/core/test/snapshot-multiple.test.js
This PR fixes two small bugs related to snapshot options validation.
1. **Do not pre-scrub empty snapshot lists.** When pre-scrubbed, empty lists are removed and cause warnings due to the missing property. By adding back an empty array when needed, the incorrect validate warning no longer occurs.
2. **Remove method of validation error suppression.** Before schemas could be properly inherited, a check would ensure that errors bubbled from the correct schema. Now with inheritance, errors can bubble from related schemas as well.
> 🐛 Core snapshot validation bug fixes

- packages/cli-command/bin/readme.js
- packages/cli-command/package.json
It seems this script was never properly tested before release. This PR fixes a couple of reference errors and adds a file extension which is required of scripts within ESM packages.
> 🐛 Fix readme generation script

- packages/config/src/utils/merge.js
- packages/config/src/utils/normalize.js
- packages/config/test/index.test.js
This PR allows the normalization config util to accept a custom `skip` option and also ensures normalization is always skipped for class instance properties.
Also, to avoid infinite recursion when merging objects with circular references, such objects are ignored completely during a merge. If we absolutely need to handle creating circular references in the future, we might need to refactor the current merge strategy.
> ✨@percy/config util improvements

- packages/cli/src/commands.js
- packages/cli/test/commands.test.js
When working on CLI plugins, like the Storybook SDK, it can be useful to be able to manually test the plugin without releasing it or linking it in another project. This PR adds package.json detection in the current directory so the `percy` command can now autoload a CLI plugin the plugin's own directory.
> ✨ Autoload CLI plugin from the current working directory

- packages/core/src/snapshot.js
- packages/core/test/snapshot.test.js
When alternate snapshot syntaxes were introduced, the validation schema is determined by checking for specific snapshot options. For DOM snapshots, we check for the `domSnapshot` option. However, property normalization is based on the determined schema (such as not normalizing headers for example). Therefore, when determining which schema to use, the options have yet to be normalized. For all other syntaxes, this is no problem. For DOM snapshots however, the accepted property can be either `domSnapshot`, `dom-snapshot`, or `dom_snapshot` (as seen [here in the capybara SDK](https://github.com/percy/percy-capybara/blob/master/lib/percy/capybara.rb#L31)).
This PR updates the schema check to account for these possible combinations of dom snapshot properties. A relevant test was also updated …
> 🐛 Check for alternate casing when determining dom snapshot syntax

- packages/config/src/utils/normalize.js
The `@percy/config` util, `normalize`, recent received a `skip` option. However the option was implemented to skip all or nothing; i.e. completely skipping normalizing higher level keys if a lower level key was intended to be skipped. 
By moving the skip check to within the key map loop during normalization, it allows the opportunity to skip any one specific key within the value's key-path array.
> 🐛 Make config normalize skip option behave as expected

- packages/logger/src/logger.js
- packages/logger/test/helpers.js
- packages/logger/test/logger.test.js
In #916 the logger was refactored slightly. While doing so, I misread Node docs that `cursorTo` returned `this`. 
Turns out, it returns a boolean.
> 🐛 Fix logger TTY logic for logging progress

- packages/sdk-utils/src/logger.js
- packages/sdk-utils/test/helpers.js
Since our sdk-utils logger got a little less sophisticated, so did how we mock it during tests. However, the simple mock was a little too simple and would sometimes capture logs that it didn't need to.
This PR updates the sdk-utils test helper to only capture logs during a `logger.log()` call. Usage of `log()` or `log.bind()` within the file was updated to include the `logger` namespace so stubs work no matter when a logging group was created.
> 🐛 Fix sdk-utils test helper log capture

- packages/cli-snapshot/test/directory.test.js
- packages/cli-snapshot/test/file.test.js
- packages/cli-snapshot/test/sitemap.test.js
- packages/core/src/snapshot.js
- packages/core/test/snapshot-multiple.test.js
When given a path such as `/index.html`, the fallback regular expression matching would match anything containing the string, including paths such as `/other-path/index.html`.
This PR fixes the issue by not using the predicate as a fallback regular expression. To use a regular expression pattern, the pattern should look like: `/regex-here/` (like a normal JS regular expression).
I also adjusted two merge snapshot option paths that I noticed were being logged as empty arrays.
> 🐛 Fix regex matching accepting non-regex patterns

- packages/core/src/snapshot.js
Sometimes when there's other content inside of a sitemap `<loc>` (like `<image:image>`), the current regex will keep matching. This causes the URLs to include invalid content, making the snapshot(s) fail. The `?` makes the regex not greedy and it'll stop matching when the lookahead matches.
> 🐛 Fix sitemap xml parsing regex (stop when the lookahead matches)

- packages/cli-upload/test/upload.test.js
- packages/client/src/client.js
- packages/client/test/client.test.js
- packages/core/src/config.js
- packages/core/src/snapshot.js
Add a snapshot option to scope a screenshot down to a specific selector. This currently won't work since it relies on infrastructure & API changes to be made, but now the SDKs will pass this option to the API.
> ✨ Introduce `scope` snapshot option

- packages/sdk-utils/package.json
This PR fixes browser based SDKs from grabbing the wrong bundle for the wrong environment. Currently they may try to use the node bundle (`index.js`), when it should be using the browser complied version (`bundle.js`). https://webpack.js.org/guides/package-exports/#providing-different-versions-depending-on-target-environment
> 🐛 Fix `@percy/sdk-utils` exports field for browser based SDKs

- packages/core/src/config.js
- packages/core/src/page.js
- packages/core/src/snapshot.js
- packages/core/test/discovery.test.js
- packages/core/test/percy.test.js
With the addition of real native devices in our rendering infrastructure, we now need to capture 2x++ pixel images for pages to render properly (since the real devices have high pixel density screens).
With the new `devicePixelRatio` config option, we now will resize the browser to each specified width at 1x and also whatever the passed value is for `devicePixelRatio`. We also run both `beforeResize` and `afterResize` events with the additional scale resizes. These assets are discovered in their own tab, separate from 1x devicePixelRatio assets to ensure that the right scaled assets are loaded (rather than trying to resize and reset the devicePixelRatio)
> ✨ Capture different pixel densities in asset discovery

- packages/core/src/discovery.js
- packages/core/test/discovery.test.js
In https://github.com/percy/cli/pull/921 we realized font responses were being corrupted through the browsers request interception API. To get around that, we now request and save fonts straight from node as a binary (no encoding). In that PR, I forgot to pass the auth config to the request that's being made, which will prevent sites behind auth from capturing fonts properly.
This PR adds the request headers the browser has to the node request we made to capture the fonts directly. Also adds a debug log when we are requesting these fonts directly. 
Closes #969
> 🐛 Pass auth headers when requesting assets directly

- packages/config/src/utils/normalize.js
- packages/config/test/index.test.js
While creating the .NET SDK, I noticed that the convention in that land seems to be PascalCase object properties, and as everything is an object, some people might create PascalCase snapshot options objects. However our options normalization does not handle the first word of keys. So even a key of `ALLOWED_HOSTNAMES` would end up becoming `ALLOWEDHostnames`.
With the changes in this PR, the config normalization helpers will now split all words regardless of casing, then convert to the desired casing. Not only does this enable PascalCase options, but will now handle all-caps underscore or even option names with spaces (like `network-idle timeout` but who would do that?).
> ✨ Allow PascalCase options (and other casing)

- packages/core/src/api.js
- packages/core/test/api.test.js
During testing mode, full logs are rarely useful, but individual snapshot logs are more important to test against. Clearing logs on reset will allow SDK tests to read only recent and relevant logs without having to filter them.
> ✨ In testing mode, clear logs on reset

- packages/core/src/discovery.js
- packages/core/src/network.js
- packages/core/test/discovery.test.js
Turns out when using the `authorization` config in `.percy.yml` (where you pass a username/password rather than encoding it as a header), those aren't passed as request headers. So simply grabbing the same headers and passing them to the node request won't work here. We need to check if the `authorization` config exists and if it does, apply that header to the Node request.
> 🐛 Pass authorization config to asset discovery direct requests

- packages/cli-snapshot/src/snapshot.js
- packages/cli-snapshot/test/directory.test.js
- packages/cli-snapshot/test/file.test.js
- packages/core/src/percy.js
- packages/core/test/snapshot.test.js
This new `delayUploads` option is an alternative to the existing `deferUploads` option. With the existing `deferUploads` option, all uploads (including build creation) are deferred until the instance is stopped. With the new `delayUploads` option, an upload is not processed until the next upload is queued. So the build is not created until the first snapshot is taken, and that snapshot is not uploaded until the next snapshot is taken, and so on until the last snapshot is uploaded when the instance is stopped and the build is finalized.
Currently, this is only useful to speed up the snapshot and storybook commands since those are the only SDKs that utilize `deferUploads` and will error when no snapshots are found. In the future, this could become an opt-in feature for the exec command for …
> ✨ Add option to delay uploads without deferring until the end

- packages/config/src/validate.js
- packages/config/test/index.test.js
- packages/core/test/snapshot.test.js
When providing additional snapshots with both a `name` and a `prefix`/`suffix`, a warning is logged that only `name` will be used. However, with the way our config validation works, any property that results in a schema error (that isn't handled by other constraints) will be scrubbed. This means that the warning is incorrect, and the additional snapshot is disregarded entirely when providing both a `name` and a `prefix`/`suffix`.
This is fixed within our validation wrapper by _not_ scrubbing properties that are failing by actually passing more than a single schema (specifically the `oneOf` schema). The property is still scrubbed when there are zero passing schemas.
Another expectation was also added to core tests to verify the desired behavior of the additional snapshot being kept.
> 🐛 Fix config being scrubbed from passing schemas

- packages/core/src/percy.js
- packages/core/test/snapshot.test.js
This fixes a bug with the new `delayUploads` option being combined with the `--debug` flag.
Different than the `dryRun` option, the `skipUploads` option may be provided while debugging so snapshots are still processed by asset discovery without a build being created. The `dryRun` option implies `skipUploads`, so this change does not affect existing dry-run behavior.
> 🐛 Do not start delayed uploads when debugging

- rollup.config.js
Some older implementations of AMD module loading systems might throw an error when the first argument to define a module is not the name of the module itself. This PR adds the package name to the AMD section of the generated bundle output for rollup builds.
> 🐛 Improve compatibility with AMD module systems

- packages/core/src/utils.js
- packages/core/test/snapshot.test.js
When providing a string as a value for `execute` options, it will be disregarded as unserializable if the string contains a function signature. For example, this was previously "unserializable": `"function () { ... }"`
With this PR, the provided string is checked for a function signature before being automatically given one.
> 🐛 Check for execute signature before handling as function body

- packages/client/test/helpers.js
- packages/core/src/percy.js
- packages/core/test/snapshot.test.js
Uploads are deferred by flushing the upload queue when stopping. Uploads are delayed by running the queue before adding to it, stopping it again when an upload begins, and finally flushing when stopping. However, because the queue gets stopped when an upload begins, flushing causes the upload task to stop the flush from continuing. This causes builds with delayed snapshots to prematurely stop uploading and finalize the build before it should be.
This is fixed by only stopping the queue for delayed uploads when the instance itself is not stopping. When the instance stops, uploads should be processed accordingly with any set concurrency.
The test I added was not failing due to the mock API responding too fast to uploads, causing the queue to be drained before stopping. I found that adding a …
> 🐛 Only delay uploads when actively running

- packages/cli-snapshot/src/snapshot.js
- packages/cli-snapshot/test/file.test.js
- packages/config/src/load.js
- packages/config/test/helpers.js
As the title suggests, this PR adds support for loading `.cjs` config files and snapshot files. 
This PR also adds support for `.mjs` snapshot files, but **not** config files (cosmiconfig does not support esm files).
Closes #1007
> ✨ Add support for .cjs config files and snapshot files

- packages/logger/src/logger.js
- packages/logger/test/logger.test.js
This PR addresses two small issues with logger and adds another small feature.
- Some URLs don't get fully colored properly in log output. This is fixed with a more verbose URL regular expression.
- In non TTY environments colors aren't always supported and produce raw ansi output. This is fixed by only using colors for TTY stdout streams.
- Depending on the SDK/integration, it can sometimes be beneficial to hook into or override some logging behavior. This is made possible for our logger by moving message formatting into the write method so we can pass along the full log payloads. With full payloads, one is able to set a custom `logger.instance.write` method to handle log output.
Thanks to @grachov for the ideas with #953 & #961.
> ✨ Improve logger functionality

- packages/cli-build/src/wait.js
- packages/cli-build/test/wait.test.js
- packages/client/src/client.js
- packages/client/test/client.test.js
With the `build:wait` command, a project and commit can be provided to search for a build to wait on. However, sometimes the `HEAD` commit, or even local CI environment variables, can refer to a merge commit instead of the branch commit. When a build is created, we use the correct commit in most environments. However when a user provides a commit to the `build:wait` command, it might not match the commit that was used when creating the build. This causes the API to return an empty list since there are no builds associated with that commit for a project.
This PR addresses this issue in two primary ways. First, the command will log `Waiting for build...` when the API returns an empty list. This is because this command can be started before a build is actually created, and will update with …
> ✨ Use env sha for build:wait when there's a project with no commit

- packages/cli-snapshot/src/snapshot.js
- packages/cli-snapshot/test/file.test.js
When using the `percy snapshot` command with a snapshots file, we previously were relaxed about top-level options so YAML files could make use of references and anchors. Since moving some `cli-snapshot` features into `core`, top-level options became more strict as other types of files can now be provided (such as sitemap/static server options).
While references still work, they now inadvertently produce a validation warning (#898). This PR removes this warning for the `references` property specifically by removing that property from the config object before passing it along to the snapshot method. While we previously allowed any name for references, going forward they should be kept to the `references` property, otherwise the validation warning will be logged.
Fixes #898
> 🐛 Fix cli-snapshot warning for top-level references option

- .eslintrc
- packages/cli-exec/src/start.js
- packages/cli-snapshot/test/directory.test.js
- packages/cli-snapshot/test/file.test.js
- packages/core/src/percy.js
- packages/core/src/snapshot.js
- packages/core/src/utils.js
- packages/core/test/unit/utils.test.js
Currently, when taking bulk snapshots by either providing an array of snapshots or a snapshots function, a few aspects of the process cannot be aborted as expected, and instead get aborted after running asynchronously.
This PR adds a few core generator utils to create generators from promises (`yieldTo`) and handle running generators concurrently (`yieldAll`). The `yieldTo` util was also made to handle other values besides promises so `yieldAll` can behave similarly to `Promise.all` while still yielding to each generator.
With the help of these additional utils, bulk snapshots processing can now better handle aborting (by using generators instead of promises). A couple of other places were also adapted with these utils, as well as unit tests were added.
> 🐛 Improve aborting during bulk snapshots

- packages/core/src/utils.js
Some versions of V8 complain about promise rejections if there is no detected catch handler. Even though we await on these promises and allow them to reject asynchronously, the error can still surface as "PromiseRejectionHandledWarning: Promise rejection was handled asynchronously."
This is fixed by using then with a catch handler instead of a single finally. The promise reference no longer needs to be updated since it would cause issues to be swallowed.
> 🐛 Use then instead of finally for promises with the yieldTo util

- packages/core/src/utils.js
While #1016 attempted to fix an error in some versions of Node, it caused another error in other versions of Node. These type of errors can be avoided completely by always explicitly handling promise resolution and rejection.
> 🐛 Explicitly handle yieldTo promise resolution and rejection

- packages/config/src/validate.js
- packages/config/test/index.test.js
While adjusting the config schema for Storybook, there's a requirement to conditionally validate some properties. Specifically, when JavaScript is enabled, DOM capture options cannot be used. While this can be partially achieved with the current `@percy/config` package, this PR makes some adjustments to not only make it easier, but to also add the ability for more broad config validations.
First, we currently suppress confusing validation warnings from `allOf`, `oneOf`, `anyOf`, and `not`. This is because the default validation warnings are _always_ generated even if that schema is not the best match. For example, if `anyOf` is used to accept both a number or an array of numbers, the default warnings would show at least one failure since both cannot be true, but the whole schema is valid …
> ✨ Config schema and validation improvements

- packages/core/types/index.d.ts
- packages/core/types/index.test-d.ts
We were missing `devicePixelRatio` & `scope` in the TS typedefs. This will close https://github.com/percy/percy-playwright/issues/115
> 🐛 Update snapshot typedefs

- packages/core/src/api.js
With #1031, testing mode was updated to support disconnecting remote logging connections. This was done mostly for `@percy/sdk-utils` tests themselves because in practice, SDK tests should only need to connect remotely once.
Currently having remote connections disconnect and reconnect between each test causes unnecessary load and can sometimes even cause SDK tests to hang. By avoiding this implicit disconnect we can avoid SDK test flakes/hangs. 
Connections can still be explicitly disconnected with the `remote-logging` command, which enables `@percy/sdk-utils` tests to continue to exist as-is without changes.
> 🐛 Do not implicitly reset testing mode remote connections

- packages/cli-command/README.md
- packages/cli-command/src/command.js
- packages/cli-command/test/flags.test.js
- packages/cli-upload/src/upload.js
- packages/core/src/percy.js
- packages/core/src/snapshot.js
- packages/core/test/discovery.test.js
While asset discovery is usually necessary for taking DOM snapshots, sometimes we don't actually need to take DOM snapshots at all, such as with the `upload` command. For these circumstances, downloading a browser for asset discovery that won't ever be used is unnecessary.
For the `upload` command, we currently have a 2-part approach to skipping asset discovery. First, we utilize a `@percy/cli-command` specific option, `discoveryFlags`, to suppress asset discovery flags from being accepted. Second, we provide the `percy.start()` method with an option to skip launching a browser, which in-turn prevents the browser download completely.
For future projects, this 2-part solution isn't possible, and even now seems like a workaround for a missing feature. This PR adds that missing feature: an …
> ✨Add core option to skip asset discovery

- packages/cli/src/update.js
- packages/cli/test/update.test.js
- packages/logger/src/logger.js
- packages/logger/test/logger.test.js
When adding a label to a log message, the label should be added after any leading newlines. Likewise, debug timestamps should be added before any trailing newlines. This is currently useful for the version check log, however will also be utilized for a future planned feature.
> ✨ Format logger messages padded by newlines

- packages/core/src/api.js
- packages/core/src/snapshot.js
- packages/core/test/snapshot-multiple.test.js
The base-url option for static servers wasn't working correctly for two reasons. First, is the assumed sitemap URL was being constructed in a way that would leave off trailing paths from URLs, like how relative links work. Second, when creating a static server, the generated sitemap was only being served at the server root, not at the base-url root.
The first part of the issue is fixed by ensuring that any provided base-url has a trailing forward slash so when the URL is constructed, it treats the base-url as the path root. The second part is fixed by adjusting static server creation to host the generated sitemap at the correct path under the base-url.
> 🐛 Fix static server base-url issue

- packages/cli-app/LICENSE
- packages/cli-app/README.md
- packages/cli-app/package.json
- packages/cli-app/src/app.js
- packages/cli-app/src/exec.js
- packages/cli-app/src/index.js
- packages/cli-app/test/.eslintrc
- packages/cli-app/test/exec.test.js
- packages/cli-exec/README.md
- packages/cli-exec/src/ping.js
- packages/cli-exec/src/start.js
- packages/cli-exec/src/stop.js
We are currently working on support for native app screenshots, in which the browser download normally done by the `exec` command is wholly unnecessary. With the new `skipDiscovery` option introduced with #1038, we could map a flag or environment variable to enable this option, however there might still be future difference we wish to separate by means of an entirely new CLI command namespace.
This PR introduces that new namespace, `percy app`. Currently all subcommands are very thin wrappers for the `exec` commands which enables `skipDiscovery` while changing the commands help output description slightly. The plan is for native apps to use `percy app:exec` instead of `percy exec` (and similarly with `app:exec:start`).
Currently, this PR uses a `hidden` command warning since it isn't …
> ✨ Add hidden CLI app command for future SDKs

- packages/cli-build/README.md
While #1041 added a new `build:id` command, I forgot to update the readme. This PR does that.
> 📝 Update cli-build readme with build:id command

- packages/dom/src/serialize-cssom.js
- packages/dom/test/serialize-css.test.js
Previously, we excluded serializing CSSOM rules that were already seemingly included in the document. However, JavaScript on the page can still manipulate this CSSOM without updating the document, which prevents some CSSOM changes from being properly serialized. By removing this exclusion, existing CSSOM style content will also be serialized, which will include any manipulated CSSOM.
I removed two tests as a result of this change. One test regarding a whitespace check since the check is no longer performed. The other being a test to ensure an existing stylesheet wasn't serialized. It is now serialized on purpose, resulting in this test being counter to what we want. We still don't want to serialize external stylesheets, which is now caught by missing coverage, so a `link` element was …
> 🐛 Serialize all CSSOM rules

- packages/cli-snapshot/src/snapshot.js
When using the `percy snapshot` command and importing a snapshot file on Windows, the drive letter can sometimes get interpreted as a URL protocol, which causes the import to fail. By using an explicit file URL with a `file://` protocol, the import will work in all environments. This PR updates the snapshot file import to use `URL.pathToFileURL()` which will also automatically resolve the absolute path like we were doing before.
This was likely missed by our Windows CI due to mocked ES modules and the mocked filesystem. Unfortunately there isn't much to do to test for this without undoing the mocks and writing a real file when running tests in Windows.
> 🐛 Use a file URL when importing snapshot files

- packages/dom/src/serialize-cssom.js
- packages/dom/test/helpers.js
- packages/dom/test/serialize-css.test.js
With #1051, CSSOM serialization was made to be much more relaxed, serializing all available document stylesheets. This seems to be problematic in some instances with non-standard vendor prefixed CSS rules.
This PR attempts to avoid serializing these stylesheets while preserving the original goal of #1051, to serialized modified stylesheets. To do this, a check is added to compare the cloned stylesheet with the original stylesheet, and only serialize those stylesheets that do not already match.
Tests were updated to include a modified stylesheet and expectations changed to expect the unmodified stylesheet to not be serialized.
> 🐛 Restrict CSSOM serialization to modified stylesheets

- packages/sdk-utils/src/logger.js
It seems that the WebSocket constructor can sometimes cause browsers to hang during the initial handshake. This PR adjusts `@percy/sdk-utils` remote logger connection to start the timeout immediately, before a WebSocket is even created. This should cause the resulting promise to be rejected if the WebSocket constructor hangs for more than the default 1s timeout. This timeout is not visible outside of debug logs since remote logging connections aren't required for SDKs to work with the CLI. Unfortunately, a test for this cannot be added without blocking the event loop.
> 🐛 Fix sdk-utils websocket constructor hanging

- packages/core/src/api.js
- packages/core/src/server.js
- packages/core/test/api.test.js
- packages/core/test/unit/server.test.js
- packages/sdk-utils/README.md
- packages/sdk-utils/src/logger.js
- packages/sdk-utils/src/percy-enabled.js
- packages/sdk-utils/test/helpers.js
- packages/sdk-utils/test/index.test.js
The remote logger is a nice to have to get logs from remote browsers/clients, but it's not required. We've noticed that websockets have been hanging up suites (#1065). Rather than chasing this nice to have, we're going to remove it since it's not that big of a feature to begin with. 
Will close #1065
> 🐛 Remove remote logger

- packages/cli-snapshot/src/config.js
- packages/cli-snapshot/src/snapshot.js
- packages/cli-snapshot/test/unit/config.test.js
- packages/core/src/config.js
- packages/core/test/snapshot.test.js
- packages/core/test/unit/config.test.js
This PR removes options were meant to be removed with 1.0.0, but snuck past and stuck around a bit long.
The core snapshot list migration was left empty but will be reused for a future deprecation.
> 🗑 Remove deprecated pre-release options

- packages/core/src/config.js
- packages/core/src/snapshot.js
- packages/core/test/discovery.test.js
- packages/core/test/snapshot.test.js
- packages/core/test/unit/config.test.js
The `devicePixelRatio` option is only used in asset discovery and was meant to be nested with related snapshot asset discovery options. This PR corrects the location of this option and adds a new deprecation notice for the old location.
> ♻️ Move devicePixelRatio snapshot discovery option

- packages/sdk-utils/src/logger.js
- packages/sdk-utils/test/helpers.js
- packages/sdk-utils/test/index.test.js
With #254 and the removal of remote logging, SDK tests will need to be updated to mock local logs. Rather than needing to replicate mocking code for each SDK, we can simply replace the internal log function with our own mock. This mock cannot be tested like a normal mock or spy (no calls or argument tracking). Instead, this mock very minimally mimics the original logging code, without colors, and pushes logs into appropriate arrays for testing.
I moved logger test setup code back into the logger suite so the other tests could use the new mock helper. This revealed a few lines of missing coverage that required another log be added to the two existing tests. Log history tracking was also removed since it was only used for sending to remote connections, which then prompted the linter to …
> 🐛 Add sdk-utils logger mocking test helpers

- packages/cli-upload/src/upload.js
- packages/cli-upload/src/utils.js
- packages/cli-upload/test/upload.test.js
- packages/core/src/api.js
- packages/core/src/discovery.js
- packages/core/src/network.js
- packages/core/src/page.js
- packages/core/src/percy.js
- packages/core/src/queue.js
- packages/core/src/snapshot.js
- packages/core/test/discovery.test.js
- packages/core/test/percy.test.js
- packages/core/test/snapshot-multiple.test.js
- packages/core/test/snapshot.test.js
- packages/core/test/unit/queue.test.js
This PR refactors the queues in `@percy/core` to allow greater encapsulation and functionality. Queue specific tasks were grouped together and as a result caused other parts of core to be slightly refactored.
The queue class previously allowed arbitrary task functions to be queued together and run concurrently. All discovery related queued tasks did the same thing, but with different snapshots. Likewise with the upload queue, with the exception of deferred build creation.
The new queue class allows queuing arbitrary _items_ and processes them concurrently using configured handlers. The discovery queue is configured to first launch a browser before processing items (discovering resources). The snapshots queue is configured to create and finalize a build around processing items (uploading …
> ♻️ Refactor core queues

- packages/cli-upload/src/upload.js
- packages/cli-upload/src/utils.js
- packages/core/src/discovery.js
- packages/core/src/percy.js
- packages/core/src/snapshot.js
- packages/core/test/percy.test.js
This PR continues some of the refactor work started with #1077. In that PR, the upload command needed a new upload method, so a quick one was implemented. This PR polishes the upload command and moves some related logs around within the queues. This further isolates queue features from each other and also sets the stage for the core upload method and snapshot queue to accept alternate API requests (such as a future comparisons API).
> ♻️ Adjust how direct snapshot uploads are handled

- packages/config/src/utils/normalize.js
- packages/config/test/index.test.js
Our `normalize` config utility allows transforming object keys to a different casing while removing empty values from the provided object. Currently, it supports transforming object keys from any casing into either camelCase or kebab-case. This PR adds the ability to transform keys into snake_case by copying the kebab-case functionality and replacing `-` with `_`.
> ✨ Add snake_case normalization to config utils

- packages/core/src/api.js
- packages/core/src/config.js
- packages/core/src/percy.js
- packages/core/src/queue.js
- packages/core/test/api.test.js
- packages/core/test/percy.test.js
- packages/core/test/unit/queue.test.js
- packages/sdk-utils/src/flush-snapshots.js
- packages/sdk-utils/src/index.js
- packages/sdk-utils/test/index.test.js
For some time, our internal queues have been able to be deferred so snapshots are only processed and uploaded after asset discovery has completely finished for all snapshots. This was only ever utilized in a couple of SDKs which specifically did not create empty builds when no snapshots were found (storybook and the upload command). With the recent refactor around our internal queues, deferred items can now be cancelled or merged with existing deferred items to allow better encapsulation and greater control over internal queues.
This PR not only exposes the `deferUploads` option via a new config file entry, but also exposes a new core endpoint to flush deferred snapshots. The core flush method was also updated to accept one or more specific snapshots to flush rather than flush all …
> ✨ Expose deferred uploads

- packages/core/src/discovery.js
- packages/core/src/snapshot.js
- packages/core/test/snapshot.test.js
While testing multi-dom support with the snapshot command, I noticed two issues that this PR fixes.
1. When both `delayUploads` and `deferUploads` are `true`, the snapshot queue acts delayed but not deferred. This is fixed by checking for `!deferUploads` before automatically flushing the queue.
2. When the first snapshot is taken at the initial width, it is missing it's singular `width`. This happened because `width` was undefined for the first loop, and fixed by setting it to the first width.
One test was updated to test for both of these issues. First `delayUploads` was added to ensure it does not affect `deferUploads`. Second, debug logging was added to test for a specific snapshot log to verify each singular width.
> 🐛 Fix multi-dom capture when using the snapshot command

- packages/client/README.md
- packages/client/src/client.js
- packages/client/test/client.test.js
- packages/client/test/helpers.js
- packages/core/src/api.js
- packages/core/src/config.js
- packages/core/src/percy.js
- packages/core/src/snapshot.js
- packages/core/test/api.test.js
- packages/core/test/percy.test.js
- packages/sdk-utils/src/index.js
- packages/sdk-utils/src/post-comparison.js
- packages/sdk-utils/test/index.test.js
Soon, the Percy API will be able to accept specific snapshot comparisons to upload and associate with a build. This PR adds methods to `@percy/client` and `@percy/core` to enable SDKs to communicate with this upcoming API.
Comparison methods added to client mirror other snapshot methods already present, with a few changes. For example, comparison creation and finalization is similar to snapshot creation and finalization, but with different endpoints and payloads. Likewise for snapshot resources and comparison tiles. The only major difference between the two APIs, is the comparisons flow includes creating a parent snapshot first, but not finalizing it.
Other small changes were made such as repurposing the build ID validation function to validate any type of ID, and using `fs.promises` to …
> ✨ Add comparisons API for future SDK usage

- packages/core/src/network.js
- packages/core/src/page.js
- packages/core/src/session.js
- packages/core/test/discovery.test.js
Sometimes asset discovery navigation to a snapshot fails due to hanging requests or the load event never firing on the page that's being loaded. In order to help make debugging easier, we're now logging network requests that are hanging/still active when trying to navigate.
We also now suppress not needed error messages from page clean up from in-flight requests. This is most commonly logged when asset discovery is closing and external requests haven't completed.
> ✨ Show network logs on navigation errors

- packages/cli/src/update.js
- packages/cli/test/update.test.js
**Problem**
When running in CI environments, the cache file would normally be cached along with the project's dependencies. However, for some projects that do not cache dependencies, the GitHub request will always occur when the CLI runs after installation. This can sometimes cause the CLI to hang depending on rate limits or the presence of any locally defined GitHub token.
fixes #1058
**solution**
* we're exposing an environment variable that will skip this update check.
---
**Testing**
* post code changes are done
```sh
yarn lint
yarn build
```
* mock edited `node_modules/@percy/cli/.releases` file with new release `v1.14.0` in cache file(doesn't exist in github releases).
* run cli 
```sh
➜  cli git:(jigar/skip_github_update_check) ✗ export PERCY_LOGLEVEL=debug   
➜  cli …
```
> :sparkles: Skip github update check if `PERCY_SKIP_UPDATE_CHECK` is truthy

- packages/sdk-utils/src/post-comparison.js
- We need this response in SDKs so that we can parse `link` from it
> ✨ Return comparison response in sdk-utils

- packages/core/src/config.js
- For comparison tags we have backend validation for <= 10000. Making this consistent
> ✨  Updated comparisonSchema to set max width to 10000

- packages/core/src/config.js
- packages/core/src/discovery.js
- packages/core/src/network.js
- packages/core/src/snapshot.js
- packages/core/test/snapshot.test.js
This PR expands on how DOM snapshots are accepted to build towards addressing both serialized assets and also any future DOM serialization warnings. Primarily, this PR addresses accepting additional serialized DOM options in core that will enable `@percy/dom` to make serialized assets external rather than embedded in a follow up PR.
The config schema for DOM snapshots was updated to allow additional `domSnapshot` options:
- `domSnapshot.html` - The HTML string of the DOM. This is equivalent to providing `domSnapshot` as a string.
- `domSnapshot.warnings` - An array of warning strings to be logged when encountered during snapshot validation.
- `domSnapshot.resources` - An array of resource objects that will be converted to proper snapshot resources:
- `resource.url` - The complete URL of …
> ✨ Accept serialized DOM resources

- packages/core/test/percy.test.js
- packages/dom/src/prepare-dom.js
- packages/dom/src/serialize-canvas.js
- packages/dom/src/serialize-cssom.js
- packages/dom/src/serialize-dom.js
- packages/dom/src/serialize-frames.js
- packages/dom/src/serialize-inputs.js
- packages/dom/src/serialize-video.js
- packages/dom/src/utils.js
- packages/dom/test/helpers.js
- packages/dom/test/serialize-canvas.test.js
- packages/dom/test/serialize-dom.test.js
- packages/dom/test/serialize-frames.test.js
- packages/dom/test/serialize-videos.test.js
As part 2 of #1135, this PR refactors `@percy/dom` slightly to return the new `domSnapshot` options. To track warnings and resources throughout our serialize functions, a new context object is used to keep references of the DOM, the clone, and new sets for warnings and resources.
To exercise this new serialization return format, the canvas and video serialization functions were adjusted to create new resource objects (tracked by the `resources` context set). The frame serialization function was also updated to recursively merge the resulting frame warnings and resources.
While changing the code to update the src/poster attributes to the fake resource URLs, I noticed that the browser would actively make these requests immediately even though the cloned DOM is not mounted. To workaround …
> ✨ Serialize DOM resources

- packages/client/src/client.js
- packages/client/src/utils.js
- packages/client/test/client.test.js
- packages/core/src/config.js
- yarn.lock
- update tile config to include sha
- skip uploading step when sha is present for tiles
> ✨ skip upload when sha is present

- packages/core/src/discovery.js
- packages/core/src/snapshot.js
- packages/core/test/discovery.test.js
device-pixel-ratio setting in config was not getting passed down to asset discovery function. This fixes that
>  🐛 fix device pixel ratio config for percy exec

- packages/cli/src/update.js
- packages/cli/test/update.test.js
* Disallow pushing users to switch to Alpha/Beta or prerelease versions.
**behavior previously**
```sh
[percy] A new version of @percy/cli is available! 1.16.0 -> 1.19.1-alpha.0
```
**behavior henceforth**
```sh
[percy] A new version of @percy/cli is available! 1.16.0 -> 1.17.0
```
> :broom: don't show prerelease versions for update in CLI

- packages/cli/README.md
- packages/core/README.md
- packages/dom/src/clone-dom.js
- packages/dom/src/inject-polyfill.js
- packages/dom/src/serialize-cssom.js
- packages/dom/src/serialize-frames.js
- packages/dom/test/serialize-css.test.js
- packages/dom/test/serialize-dom.test.js
In https://github.com/percy/cli/pull/1165, we refactored our DOM cloning logic. We moved to creating a clone and adding it to a cloned node of document. This, however triggers DOM events like connectedCallback which mess up the user DOM. This PR moves from keeping the clone node in a document to a `DocumentFragment`
> ✨  DOM events triggered on clone fixed

- packages/dom/src/serialize-dom.js
- packages/dom/test/serialize-dom.test.js
* allow `domTransformation` to be passed as a string.
* This update would work for SDKs where we cannot pass it as a function (Eg. selenium etc).
> :sparkles: Allow domTransformation to be passed as string

- packages/cli-app/src/app.js
- packages/cli-command/test/help.test.js
- packages/client/src/client.js
- packages/client/test/client.test.js
- Updating verify tiles from get to post.
- Removing warning for app:exec command.
> 👷  update request method for verify tiles, remove warnings banner for app:exec

- packages/client/src/client.js
- packages/client/test/client.test.js
- we have updated verify endpoint to raise err code 400, we previously were retying on 409 hence need to update it to fix the retry logic.
- currently, if a tile is not uploaded in 500ms which is the initial wait time we throw an error.
> 👷 update error code for retry logic

- packages/dom/src/serialize-cssom.js
- packages/dom/src/utils.js
- packages/dom/test/utils.test.js
Fixes https://github.com/percy/cli/issues/1194
In order to serialize the styles, we mount them temporarily on a document clone. The presence of a content security policy on the page was blocking this from happening, throwing the following error:
```
Refused to apply inline style because it violates the following Content Security Policy directive:
```
To fix this, the node should have a [nonce](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce).
> 🐛 copy full style node for deriving CSS rules

- packages/client/src/client.js
- packages/client/test/client.test.js
Context:
- So far we passed `filepath` in the api and it was cli which used to read file to upload.
- Now we also want an option to pass file content directly as base64 in the request so that we dont need to pass filename / path
Changes:
- Updated codebase to check if content was passed and was base64 string then parse it into buffer and treat it same as content read from filepath
> Added changes to support base64 content in postComparison API

- .github/workflows/sdk-regression.yml
Runs regression tests for all SDKs when "RUN_REGRESSIONS" is commented
> 💚 Trigger CLI Regression on PR comment

- packages/core/src/discovery.js
- packages/core/test/snapshot.test.js
- packages/dom/src/utils.js
- packages/dom/test/serialize-css.test.js
Fixes https://github.com/percy/cli/issues/1204
Percy CLI Server expects base64 data for resources by default. There's no straightforward way to convert unicode javascript strings, which have a 2 byte character size to base64 in the browser. Hence, we modify CLI server to accept resources with a text mimetype with UTF8 encoding
> Serialize text resources as utf8

- .github/workflows/sdk-regression.yml
We updated SDK regression to use PR branch instead of current branch in https://github.com/percy/cli/pull/1211.  But selecting PR branch is not documented properly and we needed a merge to test it. There were issues and this plans to fix it
> Regression use PR branch

- packages/cli-build/README.md
- packages/cli-build/src/wait.js
- packages/cli-build/test/wait.test.js
- packages/client/README.md
- packages/client/src/client.js
- packages/client/test/client.test.js
* Increase polling interval for build to default to 10s.
* polling 1s is unnecessary and also causes stress on API, A build usually doesn't finish in 1s granularity. if less than 1s is given we'll clamp it to 1s
> ✨ increase interval for polling build

- packages/dom/src/clone-dom.js
- packages/dom/test/serialize-dom.test.js
WebComponents have [lifecycle callbacks](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#using_the_lifecycle_callbacks) which can mess up the structure of the page while trying to create a clone. We'd earlier fixed it for `connectedCallback` and `disconnectedCallback` in https://github.com/percy/cli/pull/1185. `attributeChangedCallback` is called before `connectedCallback` and can also cause side effects when we clone a node. We solve for this effect by asserting the shallowness of the node cloned in this PR
> 🐛 cloneNode ensure shallow clone

- .github/workflows/sdk-regression.yml
We fixed storybook and selenium ruby regression issues in https://github.com/percy/percy-storybook/pull/723 and https://github.com/percy/percy-selenium-ruby/pull/9 respectively. Now they can be added to the regression pipeline
> 👷 Add storybook & selenium ruby to regression

- .github/workflows/sdk-regression.yml
The `issue_comment` event on which we want to trigger our regression suite does not have any context on the commit or branch. Hence, it does not show up in status check by default.  Hence, we use Github API to update the status
> Regression status check

- .github/workflows/sdk-regression.yml
We don't have access to job id needed to build the URL in the action context. We fetch it using the API.
> Regression Fix job url and status update

- packages/core/src/config.js
- packages/core/src/page.js
- packages/core/test/percy.test.js
- packages/core/test/snapshot.test.js
- packages/core/test/unit/config.test.js
* `domTransformation` is a feature of `@percy/dom` package where in we can run arbitrary JS to modify the snapshotted DOM post serialization - [ref](https://github.com/percy/cli/tree/master/packages/dom#options)
* `Page.snapshot` is used by `cli-snapshot` and `percy-storybook` packages, other SDKs don't borrow `Page` from the asset discovery browser we inject `PercyDOM` script in the user's test browser. 
* With this PR cli snapshot and storybook SDK will be able to leverage `domTransformation` param.
> :sparkles: support domTransformation in Page.snapshot function

- .github/workflows/sdk-regression.yml
Branch input as is can be susceptible to injection attacks
> Regression branch validation

- packages/config/package.json
- yarn.lock
Changes:
- Updated cosmiconfig to 8.x.x
- Older version was using `yaml` 1.x.x which had open cve's, newer version has moved to `js-yaml` package as dependency 
- We still have older `yaml` as dependency as its a dependency of `lerna` as well, but as lerna is not included as dependency in final released package, it would be not distributed
> Bump cosmiconfig to 8.x.x

- packages/core/src/api.js
- packages/core/test/api.test.js
- packages/sdk-utils/src/percy-enabled.js
- packages/sdk-utils/test/helpers.js
- packages/sdk-utils/test/index.test.js
- For support of percy app:exec start/stop we need build id and url. adding as part of percy-info since we use sdk-utils in js SDK so we can make use of this and access using `percy.build.id` & `percy.build.url`
> Add build info in percy-info

- packages/dom/src/clone-dom.js
- packages/dom/src/transform-dom.js
- packages/dom/test/serialize-dom.test.js
- packages/dom/test/transform-dom.test.js
Context:
- We currently did not drop `loading="lazy"` attribute while serialising dom
- We do not scroll in discovery phase
Issue:
- We do not capture resources, especially `img` src where `loading="lazy"` attr is present and image is out of viewport
- So when we render it on percy, the full page screenshot shows broken images [ for out of first viewport images ]
Fix:
- We now drop `loading` attribute for `img` and `iframe` element
> ✨  Support loading lazy attribute 

- packages/config/test/index.test.js
- packages/core/src/config.js
- packages/core/src/discovery.js
- packages/core/test/discovery.test.js
- packages/core/test/percy.test.js
* we now introduce a new config alongside the existing `enableJavaScript` called `cliEnableJavaScript`
* purpose for this new `cliEnableJavaScript`  flag is we'll use it to override Asset discovery browser page JS before taking dom Snapshot
* since we take dom snapshot in CLI for only `cli-snapshot` ( or `percy snapshot` command) this doesn't affect `percySnapshot` ( or `percy exec --`) flow
* This change is backwards compatible and doesn't affect existing users.
* Tests are updated for a better understanding of the expectations.
> ✨ Introduce new config option for cli-snapshot for enabling JS in asset discovery page

- packages/dom/src/utils.js
- packages/dom/test/utils.test.js
Issue: https://github.com/percy/cli/issues/1246
Difficulty in showing canvas serialized images on safari browser. Fixed by replacing `localhost`  with `render.percy.local`
read more here https://docs.percy.io/docs/browsers-specific-handling#localhost-proxy-support-on-safari
> rewrite localhost domain for serialized assets to render.percy.local

- packages/cli-upload/src/upload.js
- packages/cli-upload/test/upload.test.js
- Change logic of percy upload based on type of project.
- Allow only Web and Generic project type token for upload.
> [PER-2063] Percy upload for BYOS

- packages/core/src/network.js
- packages/core/src/page.js
- packages/core/test/discovery.test.js
Added support for 2 flags as follows
1. `PERCY_NETWORK_IDLE_WAIT_TIMEOUT`: this flag is used to configure maximum time that percy cli would wait for network idle timeout to hit. i.e. if `networkIdleTimeout` is 600ms we would wait at most PERCY_NETWORK_IDLE_WAIT_TIMEOUT time to get a successful `networkIdleTimeout`.
2. `PERCY_PAGE_LOAD_TIMEOUT`: This is timeout for page_load event to fire on the page when we load page in the chromium.
Both of above are defaulted to 30000ms [ 30 sec ] and both would print a warning once per session when its set to over 60000ms [ 60 sec ].
We are adding this functionality so that in rare cases when someone wants to confirm that increasing timeout will solve the asset discovery issues for the page, they can confirm it by increasing the time.
> Added env var support for timeouts

- packages/config/package.json
- packages/core/package.json
Fixes https://github.com/percy/cli/issues/1290
I have tested this via my own application, it resolves the error I was seeing detailed in the issue. I'm no expert at this but this makes sense to me.
Please let me know if there are other steps needed to have this released & published
> chore: fix percy types exports for newer typescript

- packages/webdriver-utils/src/providers/genericProvider.js
- packages/webdriver-utils/test/providers/genericProvider.test.js
Making `freezeAnimation` false by default
> Make Freeze Animation false by default

- packages/webdriver-utils/src/metadata/desktopMetaData.js
- packages/webdriver-utils/src/metadata/mobileMetaData.js
- packages/webdriver-utils/test/metadata/desktopMetaData.test.js
- packages/webdriver-utils/test/metadata/mobileMetaData.test.js
Get Resolution details for mobile + Enhancements (x DPR)
> Adding Dpr fixes

- packages/dom/src/serialize-cssom.js
adoptedStyleSheets is supported in Safari versions from v16.4 and in automate, Safari v16.3 is only available for the latest mac os.
So if anyone uses Safari from automate to run a test for percy, the test fails with the following error:
[percy] JavascriptError: A JavaScript exception occured: undefined is not an object (evaluating 'dom.adoptedStyleSheets')
Now a check is added to verify if adoptedStyleSheets is supported. If not supported, it will show a warning and continue processing.
> Added condition to check if dom supports adoptedStyleSheets

- packages/client/src/proxy.js
- packages/client/test/unit/request.test.js
- packages/env/src/utils.js
- packages/env/test/stripQuotesAndSpaces.test.js
Added a function `stripQuotesAndSpaces` in `env/utils.js` that removes double quotes or spaces present at starting or ending of a line.
Used it in `client/src/proxy.js` where environment variable are stored in `proxyURL` & `shouldProxy`
> ✨ Update proxy.js to auto strip double quotes/spaces if any

- karma.config.cjs
- packages/core/package.json
- packages/core/src/api.js
- packages/sdk-utils/test/request.test.js
- packages/webdriver-utils/src/index.js
- packages/webdriver-utils/src/metadata/desktopMetaData.js
- packages/webdriver-utils/src/providers/automateProvider.js
- packages/webdriver-utils/src/providers/genericProvider.js
- packages/webdriver-utils/src/util/cache.js
- packages/webdriver-utils/test/metadata/desktopMetaData.test.js
- packages/webdriver-utils/test/providers/automateProvider.test.js
- packages/webdriver-utils/test/providers/genericProvider.test.js
**Context -**
- When capturing screenshots for mobile devices we have observed instances where we are also adding `nav` / `status` / `url` bars to the screenshot image.
- We want to remove these extra heights as they are **not** the part of the webpage.
- To remove these elements, we need some way to identify the device / platform / browser combination and subsequently find the heights for the sections to remove.
> feat: added support for extracting and passing header and footer heights

- packages/cli-snapshot/README.md
- packages/cli-snapshot/test/sitemap.test.js
- packages/core/src/snapshot.js
As per https://github.com/percy/cli/pull/819 `overrides` was renamed to `options` but README and some comment references were missed. Fixing it in current PR
> 🧹  Fix docs for override -> options

- packages/cli-exec/src/exec.js
- packages/cli-exec/src/start.js
- packages/cli-exec/test/exec.test.js
- packages/cli-exec/test/start.test.js
- packages/webdriver-utils/src/index.js
Support Old App Percy Tokens along with PoA projects.
We have removed the check if the projectType is of `app` for dynamic fetching of projectType. We should re-enable it when we plan from moving away from `app:exec` to `exec` for app projects.
> Support Old App Percy Tokens

- packages/core/src/network.js
- packages/core/test/discovery.test.js
What ?
- Added graceful handling of aborted requests
- Now we keep track of aborted requests and whenever we are going to make a `session.send` call we check if we have already received abortion event for same request id 
- If request was already aborted we dont print it out as `Error: Protocol error (Fetch.fulfillRequest): Invalid InterceptionId.`
- We now print two new logs under debug mode, one for aborted request event and once when we ignore error above due to the same.
Why?
- There are cases when a browser triggers a network request and cancels it before its resolved. It usually happens when a resource was originally required, but is now not required [ say you have an `srcset` with multiple entries and you change the width of the browser fast enough such that it starts loading one …
> Added graceful handling of aborted requests

- packages/core/src/snapshot.js
- packages/core/test/snapshot.test.js
What?
- By default duplicate snapshot is warning now, not error
- This warning can be suppressed with environment variable `PERCY_IGNORE_DUPLICATES` when set to true
Why?
- Some customers use `percySnapshot` in parallel tests where it gets called multiple times on multiple browsers. 
- Ideally we want customers to fix one browser and only take `percySnapshot` on that. Not multiple. But we allow customers to suppress warning as well [ we only consider first posted snapshot ]
> Added env var support to control duplicate snapshot warnings

- packages/webdriver-utils/src/driver.js
- packages/webdriver-utils/src/index.js
- packages/webdriver-utils/src/metadata/desktopMetaData.js
- packages/webdriver-utils/src/metadata/metaDataResolver.js
- packages/webdriver-utils/src/metadata/mobileMetaData.js
- packages/webdriver-utils/src/metadata/normalizeData.js
- packages/webdriver-utils/src/providers/automateProvider.js
- packages/webdriver-utils/src/providers/genericProvider.js
- packages/webdriver-utils/src/util/cache.js
- packages/webdriver-utils/test/driver.test.js
- packages/webdriver-utils/test/metadata/desktopMetaData.test.js
- packages/webdriver-utils/test/metadata/mobileMetaData.test.js
- packages/webdriver-utils/test/metadata/normalizeData.test.js
- packages/webdriver-utils/test/providers/automateProvider.test.js
- packages/webdriver-utils/test/providers/genericProvider.test.js
We have 2 protocols, which boils down to dialects `W3C` and `OSS` now `OSS` & `W3C` have different response. To make consistent and increase coverage for now we will normalize the data by adding a layer.
> Adding support for legacy protocol

- packages/core/src/network.js
- packages/core/test/discovery.test.js
Context:
- We know that browser does not return correct body for font responses to us and so we need to fetch it directly
- Now if server is not returning correct mimetype for font files [ if its sending `application/octate-stream` for example ] we didnt fetch font again as mime didnt match
- This caused errors while rendering font later in percy
Change:
- We now infer mime for all requests from url [ irrespective of original content type ] and if its font then we fetch it directly
- We dont tamper with original content type to honor browser behaviour when this gets rendered
> ✨  Checks mime for incorrect content type fonts

- .github/workflows/executable.yml
- Upload executables as assets when releasing
- While uploading assets zip also retains executable permissions no need to convert to tar
> 🏗️  Upload executables as assets

- .github/workflows/executable.yml
- scripts/executable.sh
- Move zip logic to executable script and removing from github action
- Fixes macos zip extracted as folder with 2 binaries.
> Move zip logic to executable script

- packages/webdriver-utils/src/metadata/metaDataResolver.js
- packages/webdriver-utils/test/metadata/metaDataResolver.test.js
🐛  [Fix] : Pass DeviceName if it is mobile from SDKs so that they can route to mobileResolver properly.
> Percy on Automate: Check if deviceName was passed

- packages/webdriver-utils/src/providers/genericProvider.js
- packages/webdriver-utils/test/providers/genericProvider.test.js
Removing percyCSS execution from CLI for increasing speed. The percyCSS will be executed on the required Infra to avoid latency issues.
> Removing PercyCSS from CLI for performance benefit

- packages/core/src/network.js
- packages/core/test/discovery.test.js
- packages/core/test/helpers/server.js
Changes:
- We recently updated CLI to include mimetype check for font files to use makeDirectRequest call even when font files do not return correct Content-Type in the response. 
- But the mimetype package we used does not ignore query params in url, so this fixes url by stripping query params before sending to mimetype check.
Note: We only use detected mimetype for this fetch from `makeDirectRequest ` call. We do not override original mimetype with detected mimetype unless it was originally `text/plain` [ which is existing behaviour ]
> 🐛 Fixed mimetype check for url [ for fonts ]

- packages/client/src/client.js
- packages/client/test/client.test.js
- packages/core/src/config.js
- packages/core/src/percy.js
- packages/core/test/percy.test.js
- Added support for token in percy config, under `percy.token`
- `PERCY_TOKEN` env var would still override token from config
> ✨ Added token support in percy config

- packages/env/src/utils.js
- packages/env/test/defaults.test.js
When git is not installed locally,  percy-cli triggers git popup.
We have introduced a env var `PERCY_SKIP_GIT_CHECK`. When this is set to True, git commands will not be executed locally when using percy-cli.
> [PER-2582] Do not execute git commands when `PERCY_SKIP_GIT_CHECK` is set to True

- packages/dom/src/clone-dom.js
- packages/dom/test/serialize-dom.test.js
We observed that when there are `noscript` tags are present in dom and using percy with sdk's, some icons were not getting loaded.
Asset discovery itself was not making requests to particular icon file.
This is fixed by excluding the `noscript` tags during cloning the dom.
> [PER-2574] Icons not loading when `noscript` tags are present.

- packages/core/src/config.js
- packages/core/src/discovery.js
- packages/core/src/page.js
- packages/core/test/percy.test.js
- packages/core/test/snapshot.test.js
- packages/core/types/index.d.ts
- packages/dom/README.md
- packages/dom/src/serialize-dom.js
- packages/dom/test/helpers.js
- packages/dom/test/serialize-dom.test.js
fixes https://github.com/percy/cli/issues/489
* we've seen google ads/ custom JS running in test browser causing some DOM elements to be added outside `</body>` 
* This is fine visually since most browser's don't complain about it, though according to HTML spec its not correct.
* We've logic where we regex replace last found `</body>` with percyCSS which used to fail due to these invalid tags.
* We now provide an option `reshuffleInvalidTags` which moves this visually OK, but HTML spec wise not ok elements inside `</body>` tag.
* Risks - CSS which are applied to `BODY` will now be applied to these tags - what we've also observed is these elements are generally ads iframes which are `visible:hidden` so this risk is acceptable.
* This option can be used globally for `percy snapshot` command …
> ✨ Fix percyCSS not getting applied when elements outside `</body>` 

- packages/webdriver-utils/src/driver.js
- packages/webdriver-utils/src/index.js
- packages/webdriver-utils/src/metadata/desktopMetaData.js
- packages/webdriver-utils/src/providers/automateProvider.js
- packages/webdriver-utils/src/providers/genericProvider.js
- packages/webdriver-utils/test/driver.test.js
- packages/webdriver-utils/test/metadata/desktopMetaData.test.js
- packages/webdriver-utils/test/providers/automateProvider.test.js
- packages/webdriver-utils/test/providers/genericProvider.test.js
- Maintenance - Removing Redundant Calls, Adding few debug logs, small refactoring.
> Removing Redundant Calls for PoA

- packages/webdriver-utils/src/providers/automateProvider.js
- packages/webdriver-utils/test/providers/automateProvider.test.js
In percyScreenshotEnd we currently check for `response?.body?.link` which is returned as response of postComparisons. In App Percy it works because they create comparisons before and send it's response back whereas in POA the case is not same and we create comparison later hence we send different response which does not have link causing status to be marked as failure everytime.
Now made check based on error object that if errorObj is present then only mark as failure else success. As we don't have percyScreenshotUrl in POA when this is called we are passing build url as alternative.
> Fixing percyScreenshotEnd response

- packages/core/src/config.js
- packages/core/src/discovery.js
- packages/core/src/network.js
- packages/core/src/snapshot.js
- packages/core/test/discovery.test.js
- packages/core/types/index.d.ts
**Changes**:
**Detailed Changes & Reasoning**:
- Added `Network.setBypassServiceWorker` to `bypass: false` so that we can add service-worker controller and access service worker that mocks customer's data.
- Initially tried to access service-worker requests using `Network.getResponseBody`, but over here `body` is returned as `""` _(empty string)_ randomly.
- - Tried to look on the internet about why this happens, but no luck :(
- Finally, decided to call `Network.getResponseBody` on the original request which service-worker intercepted.
- - `Network.getResponseBody` is same as what appears in the `Response` tab in Network section in devtools.
- - For requests that were intercepted by service-worker, the `Response` tab is **always** populated.
- - But the service-worker which makes the …
> Capture service worker intercepted requests

- packages/core/src/discovery.js
- packages/core/src/queue.js
- packages/core/src/snapshot.js
- packages/core/test/unit/queue.test.js
Current flushing logic wait till only the last dequeued element to be resolve the promise and as soon as that happens we take early exit. Now it can be the case that there are still the snapshots in the queue which did not got flushed. Now if queue is marked as end, we will finalize the build, but as snpashots queue still has some elements it will try to finalize those after build is finalized till the time queue is cleared.
> Resolving race condition in snapshots flush

- packages/core/src/config.js
- packages/core/src/discovery.js
- packages/core/src/network.js
- packages/core/src/snapshot.js
- packages/core/src/utils.js
- packages/core/test/discovery.test.js
- packages/core/test/unit/utils.test.js
- packages/core/types/index.d.ts
**Context-**
- Percy relies on CDP messages to intercept and capture network requests.
- CDP uses websockets, and since websockets run on TCP, at network layer it is guaranteed that the packets will always be transmitted in order.
- But at application level, packets can be processed out of order which can cause issues.
- Hence, adding a locking mechanism so that events are always processed in order at Application layer as well.
- The ideal flow of messages should be -
- - `requestWillBeSent` -> `requestPaused` -> `responseReceived` -> `loadingFinished` / `loadingFailed`
**Note:** Also merged #1443 in this PR.
> ♻️  Refactor: added defaultmap + locking mechanism for intercepts queue

- packages/core/src/network.js
- packages/core/src/server.js
- packages/core/test/unit/server.test.js
Fixes https://github.com/percy/cli/issues/1459
* Listen on dualstack `::` instead of ipv4 `0.0.0.0` for all gateways.
> 🐛  Fix connection refused for `ipv6` 

- packages/cli-upload/test/upload.test.js
- packages/client/src/client.js
- packages/client/test/client.test.js
- packages/core/src/config.js
- packages/core/src/discovery.js
- packages/core/test/unit/config.test.js
- packages/core/types/index.d.ts
- packages/core/types/index.test-d.ts
Added new option scope-options in which user can pass scroll: true/false to take scrollable single element screenshot properly
> Add support for Scrollable single element screenshot

- packages/webdriver-utils/src/providers/genericProvider.js
- packages/webdriver-utils/test/providers/genericProvider.test.js
Refactoring code to support ignoreRegions for Full Page Screenshot.
In full page screenshot Webpage can be at any scrolling state like (x,y), but the screenshot comes from the top (0,0), in that case proper scrolling factor need to be added in coordinates to get them wrt top of the DOM.
> Fixing ignoreRegions for POA Full Page

- packages/dom/test/serialize-frames.test.js
* we use `DOMParser` package to deserialize (parse) the serialized dom for testing validations.
* chrome 120 gives `about:blank` for dom parsed from the string, while chrome 119 gives iframe base URI, though serialization result in both browsers give iframe baseURI.
* The expectation of our test used to rely on the parsed dom rather the DOM directly, this PR fixes that.
> 🏗️ test fix: dom package test failing in chrome 120+

- packages/config/test/index.test.js
- packages/core/src/config.js
- packages/core/src/utils.js
- packages/core/test/api.test.js
- Add FullPage Screenshot to global config for PoA.
- This should allow to run all PoA screenshots in full page screenshots if mentioned in config file.
> Add FullPage in global config for PoA

- packages/client/src/client.js
- packages/client/src/utils.js
- packages/client/test/client.test.js
- packages/client/test/unit/request.test.js
- packages/core/src/install.js
* Adds logs of following format for `resources` and `tiles` upload endpoints. 
```
[percy:client] Uploading 692B resource:
```
* Note: it logs file size post `base64` encoding is done, which is 30% increase in file size.
* we've `25mb` file size per resource limit restriction so this log line will further help in identifying the slow uploading resource.
> ✨ Add file size logging for tiles and resources

- packages/core/src/browser.js
We got some reports that temp profile directory cleanups are sometimes failing on windows systems. The common reason was `Default\optimization_guide_prediction_model_downloads\<uuid>\visual_model_desktop.tflite` was locked and used and so we rm rf of the directory failed. 
This usually does not matter in *nix systems as you can delete files under use, but on windows the deletion fails if file is under use. So we are disabling the feature hoping that this would not keep profile directory from deletion.
Note: a failed deletion log is usually fine as its a temp dir anyway.
> 🧹 Disabling OptimizationGuideModelDownloading in resource discovery chromium

- packages/client/src/utils.js
- packages/client/test/client.test.js
- packages/client/test/unit/request.test.js
- packages/core/test/unit/server.test.js
We are seeing cases when a mitm proxy in between is either sending 403s or just blocking directly. Currently due to insufficient logging it becomes hard to understand if the 403 was due to incorrect/invalid percy token or due to a proxy in between, we are adding response body to the logs so that logs can be used to debug error right away.
> 🧹 Added logging of body for failed requests

- packages/client/src/client.js
- packages/core/src/api.js
- packages/core/src/percy.js
- packages/core/src/snapshot.js
- packages/core/test/api.test.js
- packages/core/test/snapshot.test.js
Added validation for the case where the correct token and cli flow is used but sdk used is wrong.
For exp: -> App Percy Token is used and cli server is also started using app:exec which will create correct App Percy Build but as percy_screenshot is common in both App Percy and Percy on Automate it can be possible to trigger percy_screenshot using Automate SDK which should not be the case ideally.
We are relying on build type and the endpoint called to determine which SDK would have been used and in which build
> Adding check for correct SDK for percy product

- packages/client/src/client.js
- packages/client/src/utils.js
- packages/client/test/client.test.js
Throwing error when sha, filepath or content is not present when creating a comparison.
This fixes the below error, when sha is empty, for app build.
```
Error: Finalizing build 32741978 failed: cannot finalize before all snapshots have comparisons created. This is likely an SDK error, please make sure that comparisons are created before calling finalize.
```
> Throwing error when sha, filepath or content is not present

- packages/cli-upload/test/upload.test.js
- packages/client/src/client.js
- packages/client/test/client.test.js
- packages/core/src/config.js
- packages/core/test/api.test.js
- packages/webdriver-utils/src/index.js
- scripts/test.js
adding `thTestCaseExecutionId` params to snapshot and comparison
> adding additional params for test case base grouping to snapshot and comparison

- packages/core/src/install.js
- Bumping up chromium version to v123
- This should update asset-discovery browser and should resolve shadow-root related issues.
> Bumping up chromium version to v123

- .github/workflows/sdk-regression.yml
- Updating Github action with appropriate pkg name
- Using `winterjung` instead of `jungwinter`
> Updating Github action with appropriate pkg name

- packages/dom/src/serialize-inputs.js
- packages/dom/test/serialize-inputs.test.js
In the new behaviour, if any of the radio-button have checked attribute present in the dom by default, 
it will be removed by default.
Only those radio-buttons will have `checked` attribute present in their rendered dom which are currently in checked state i.e. `element.checked` returning `true`
> Remove `checked` attr for radio-button by default

- packages/cli-exec/src/exec.js
- packages/cli-exec/test/exec.test.js
- packages/core/test/discovery.test.js
🐛  fix: In sending events in cli-exec
Github Issue -> https://github.com/percy/cli/issues/1560
Details:-
- When percy is disabled ther is no percy object created so `percy.client` is throwing us an error.
> 🐛 fix: In sending events in cli-exec

- packages/dom/src/utils.js
- packages/dom/test/utils.test.js
Github Issue: https://github.com/percy/cli/issues/1568
We can across an issue where when server defined with `127.0.0.1` instead of localhost on rails application was throwing unknown route error.
This was due to replacement of Url was not happening for it. Ficed this to replace domain with render.percy.local in both cases.
> Replace 127.0.0.1 with render.percy.local

- lerna.json
- packages/cli-app/package.json
- packages/cli-build/package.json
- packages/cli-command/package.json
- packages/cli-config/package.json
- packages/cli-exec/package.json
- packages/cli-snapshot/package.json
- packages/cli-upload/package.json
- packages/cli/package.json
- packages/client/package.json
- packages/config/package.json
- packages/core/package.json
- packages/dom/package.json
- packages/env/package.json
- packages/logger/package.json
- packages/sdk-utils/package.json
- packages/webdriver-utils/package.json
This releases a new beta version of CLI, which addresses an issue where the build breaks due to shadow DOM overwriting properties to restrict them from being accessed. We now handle such errors and allow the build to continue.
> 🔖 Release v1.28.8-beta0

- packages/core/src/api.js
- packages/core/test/api.test.js
- packages/webdriver-utils/src/index.js
- packages/webdriver-utils/src/playwrightDriver.js
- packages/webdriver-utils/src/providers/automateProvider.js
- packages/webdriver-utils/src/providers/genericProvider.js
- packages/webdriver-utils/src/providers/playwrightProvider.js
- packages/webdriver-utils/src/providers/providerResolver.js
- packages/webdriver-utils/test/playwrightDriver.test.js
- packages/webdriver-utils/test/providers/automateProvider.test.js
- packages/webdriver-utils/test/providers/genericProvider.test.js
- packages/webdriver-utils/test/providers/playwrightProvider.test.js
Changes: 
1. Made a common method captureScreenshot in WebdriverUtils which based on framework will decide to use the provider class to use for further execution.
2. Shifted few common methods like percyScreenshotBegin, percyScreenshotEnd, browserstackExecutor in genericProvider as it is being used as base class.
3. Also in constructor of these classes instead of taking each argument separately taking it as hash and assigning it to instance of object so that we can directly pass from child class without need to add every arguments from every child class.
4. For Playwright Provider we needed following things to be passed for execution 
1. Page Guid
2. MainFrame Guid
3. browserstack sessionId to make percy call.
> POA Playwright changes

- packages/core/src/percy.js
- packages/core/test/percy.test.js
Tags:
Minor fixes to validate `labels` options if getting override
> tags: minor fixes

- packages/cli-command/src/command.js
- packages/cli-command/test/command.test.js
- packages/cli-exec/src/exec.js
- packages/cli-exec/test/exec.test.js
- scripts/test.js
Adding env variable support so that if set to true we exit with status code 0 when any percy related error occurs.
`PERCY_EXIT_WITH_ZERO_ON_ERROR` is the env variable.
It won't override when customer command throws any error.
This will solve https://github.com/percy/cli/issues/1590 issue.
Ticket -> https://browserstack.atlassian.net/browse/PER-3235
> ✨  Adding env variable support so that if set to true we exit with status code 0 when any percy related error occurs.

- packages/core/src/discovery.js
- packages/core/src/page.js
- packages/core/test/discovery.test.js
- packages/dom/src/serialize-dom.js
- packages/dom/test/helpers.js
- packages/dom/test/serialize-dom.test.js
- Capture cookies using `document.cookie` in serialize-dom so can be used in asset discovery.
- Use this cookie and insert in asset discovery browser.
- Disable this behaviour using PERCY_DO_NOT_USE_CAPTURED_COOKIES env variable
- Prioritise cookie passed via percy.yml over auto captured cookie.
Note: httponly cookie can't be captured so that needs to be passed using percy.yml
> Auto capture and insert cookie in asset discovery browser

- packages/core/src/discovery.js
- packages/core/src/network.js
- packages/core/src/page.js
- packages/core/test/discovery.test.js
- Added log when capture responsive assets are on
- Move capture responsive assets logic after capturing dom snapshot (serialize-dom) earlier it is capturing dom in mobile widths when mobile browsers are enabled
> Add log for verfying if capture responsive assets is on

- packages/client/src/client.js
- packages/client/test/client.test.js
- Increase retry count for verify comparison.
- ✨  Improvement: This is to avoid timeout failures when tiles are taking time to upload.
> Increase retry count for verify comparison

- packages/core/post-install.js
Context:
As per https://github.com/percy/cli/issues/1687 we are only looking at if `PERCY_POSTINSTALL_BROWSER` env var is set and not its value. Causing us to install browser even if `PERCY_POSTINSTALL_BROWSER=false` i.e. its set to false. 
Updating check to confirm that the flag is set and value is not in 0 or false.
This still means something like `PERCY_POSTINSTALL_BROWSER=no` or `PERCY_POSTINSTALL_BROWSER=abcdf` or `PERCY_POSTINSTALL_BROWSER=null` would still trigger browser download but we are not trying to handle every possible condition and we want to be as backwards compatible as possible. 
This PR does break backwards compatibility but in obviously correct cases [ which is more like a bug in older versions ]
> Fixed behaviour of PERCY_POSTINSTALL_BROWSER

- packages/cli-build/src/finalize.js
- packages/client/src/client.js
- packages/client/test/client.test.js
- packages/core/src/percy.js
- packages/core/src/snapshot.js
- packages/core/test/percy.test.js
Jira: https://browserstack.atlassian.net/browse/PPLT-3233
Changes:
- Added cliStartTime when percy server get started first time.
> PPLT_3233: Added CLI Start Time

- packages/client/src/client.js
- packages/client/test/client.test.js
https://browserstack.atlassian.net/browse/PER-3733
adding support for source param in build post request body.
New request body atrribute for build post request to api
```
attributes: {
type: projectType,
branch: branch,
'target-branch': target.branch,
'target-commit-sha': target.commit,
'commit-sha': git.sha,
'commit-committed-at': git.committedAt,
'commit-author-name': git.authorName,
'commit-author-email': git.authorEmail,
'commit-committer-name': git.committerName,
'commit-committer-email': git.committerEmail,
'commit-message': git.message,
'pull-request-number': pullRequest,
'parallel-nonce': parallel.nonce,
'parallel-total-shards': parallel.total,
partial: this.env.partial,
tags: tagsArr,
source: source // 'user_created' or 'auto_enabled_group'
},
```
> adding support for source attribute variable internal use only

- packages/core/src/network.js
adding reponse status to processing resources
https://browserstack.atlassian.net/browse/PER-3796
```
{
"debug": "core:discovery",
"level": "debug",
"message": "Processing resource: https://percy.io/static/assets/vendor-74426c8e7d74b11701ff2c8b2ab300d5.css",
"meta": {
"snapshot": {
"name": "percy"
},
"snapshotURL": "https://www.percy.io/customers",
"url": "https://percy.io/static/assets/vendor-74426c8e7d74b11701ff2c8b2ab300d5.css",
"responseStatus": 200
},
"timestamp": 1725535454307,
"error": false
},
```
You can get the logs from `36229285` build.
> adding reponse status to processing resources

- packages/core/src/config.js
- packages/core/src/discovery.js
- packages/core/src/snapshot.js
- packages/core/src/utils.js
- packages/core/test/discovery.test.js
- packages/core/test/utils.test.js
- added waitForTimeout and waitForSelector at the time of discovery when JS is enabled 
**so now waitForTimeout and waitForSelector are at 2 places:**
- snapshot level (snapshot.waitForTimeout)
- discovery level (snapshot.discovery.waitForTimeout)
**usage of both:**
**when it is passed at snapshot level** => 
these options are used before a DOM snapshot is taken. The primary goal is to ensure that the page has fully loaded and any necessary DOM elements are present before capturing the state of the page. This mode is currently only supported when used with percy snapshot cli command.
**when it is passed at discovery level and JS is enabled** => in this phase, these options are used to wait for specific assets or network requests to be discovered and captured. The asset-discovery process …
> Adding waitForTimeout/waitForSelector for assets discovery browser when JS is enabled 

- packages/core/src/discovery.js
- packages/core/src/network.js
Context:
- Cookie parsing logic failed when cookies were encoded as base64 and had `=` at the end. 
- When servers used strict base64 cookie check this ended up with error response causing `ERR_HTTP2_PROTOCOL_ERROR` in discovery chromium. 
This PR fixes the logic and refactors the function. 
Also few unrelated logging improvements.
Secure cookie ->
- Sometime we are getting `Protocol error (Network.setCookies): Invalid cookie fields` because the percy captured cookie did not capture the secure flag
- Adding support for secure flag that can be set by setting this env variable `PERCY_SECURE_COOKIES` to true.
> Fixed cookies parsing bug in auto captured cookies

- packages/core/src/discovery.js
- packages/core/test/discovery.test.js
adding secure flag for cookies that starts with __Secure because any cookie that starts with __Secure. The browser search for secure flag.
Docs -> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
> adding secure flag for cookies that starts with __Secure

- packages/core/package.json
- packages/core/src/network.js
- yarn.lock
updating path-to-regexp to 6.3.0 where the vulnerabilities are fixed
> updating path-to-regexp to 6.3.0 where the vulnerabilities are fixed

- packages/cli-build/test/id.test.js
- packages/cli-exec/test/ping.test.js
- packages/cli-exec/test/stop.test.js
- packages/core/src/discovery.js
- packages/core/src/network.js
- packages/core/test/discovery.test.js
- packages/core/test/helpers/server.js
Context:
- We missed using cookies in the direct request done for woff2 font files
- The request object coming with cdp does not contain cookie header - mostly its added later
- So now we fetch correct cookies for url using cdp and use those cookies in direct request
> Added cookies support in direct requests

- packages/core/src/network.js
Context:
- It seems like some security softwares / or cdns have started requiring these headers - else they return 403s 
- I am assuming that addition of extra headers would not affect where its already working
> Added default headers for chromium in direct requests

- package.json
- packages/client/package.json
- packages/client/src/proxy.js
- packages/core/src/percy.js
- yarn.lock
- Added support for PAC file based Proxy
> PAC file support via PERCY_PAC_FILE_URL env var

- packages/client/src/utils.js
It will fix the bundling issue of Percy CLI lib when trying to bundle Percy inside LCNC Electron app
> Fix import in ternary statement

- packages/dom/src/clone-dom.js
- packages/dom/test/serialize-css.test.js
- packages/dom/test/serialize-dom.test.js
- Shadowroot support using getHTML
- Since `getInnerHTML` is deprecated from chrome 129 onwards and `getHTML` was introduced, serialization of shadowroot nodes needs to be updated to ensure proper working and capturing of shadowroot elements.
Release Notes:
- https://developer.chrome.com/release-notes/129#remove_non-standard_declarative_shadow_dom_serialization
MDN
- https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/getHTML
Related Chromium Tickets
- https://issues.chromium.org/issues/41490936
- https://chromestatus.com/feature/5081733588582400
> Shadowroot support using getHTML

- packages/cli-build/src/wait.js
- packages/cli-build/test/wait.test.js
- packages/core/src/api.js
- scripts/loader.js
This small PR fixes several typos to the word "receiving", which was visible on the Percy dashboard and in console logs.
> Fix 'receiving' typos

- packages/core/src/snapshot.js
- packages/core/src/utils.js
- packages/core/test/utils.test.js
- Fixing Race Condition incase of Screenshot Cmd
- Currently when calling `percyScreenshot` command the tasks were getting deleted as we used to find them using snapshot name.
- Since in screenshot command we upload comparisons they are allowed to have same snapshot name so now deletion cannot work, so we need to add find with tag name.
> Fixing Race Condition incase of Screenshot Cmd

- packages/core/types/index.d.ts
- We had missed some options in types definitions for typescript sdks
- Added missing options - updated order to be same as validator [ order doesn't matter its only for readability ]
> Added newer options in interface for typescript

- packages/core/src/network.js
- packages/core/test/discovery.test.js
- packages/core/test/percy.test.js
- Adding support for PERCY_IGNORE_TIMEOUT_ERROR env
- This will ensure that if above env is set to true, we would regardless upload snapshots instead of failing them.
> Adding support for IGNORE_TIMEOUT_ERROR env

- packages/dom/src/clone-dom.js
- packages/dom/src/serialize-dom.js
- packages/dom/test/helpers.js
- packages/dom/test/serialize-dom.test.js
Changes:
1. From chrome 131 onward, there is a restriction on serialising shadowroot elements
2. To serialise the the shadow element perfectly, we need to explicitly pass the shadowRoot elements with `getHTML`
Refer here: https://developer.mozilla.org/en-US/docs/Web/API/Element/getHTML#shadowroots
1. Tested with CLI flow ( that contains Chrome 123 )
2. Tested with firefox as test browser from versions in between (126 - 132)
3. Tested with Chrome 131 ( latest )
> Fix[ISSUE_1819]: Support for serialising ShadowRoot Element for Chrome 131 onwards

- packages/client/src/client.js
- packages/client/test/client.test.js
- packages/core/src/config.js
Adding prod build config for scanner projects to make base build as null so that they don't get compared to any other builds for alternate env support.
> Adding prodBuild param for scanner alt env

- packages/core/src/discovery.js
- packages/core/src/utils.js
- packages/core/test/utils.test.js
- yarn.lock
Issue ->
We are facing error when PERCY_GZIP is set to true.
There is some race condition where we are zipping already zipped content.
I was not able to fix the race condition but i have found a workaround for this.
How to reproduce it
Snapshot.yml
```
- name: abc
url: https://percy.io/integrations
- name: abc1
url: https://percy.io/integrations
- name: abc2
url: https://percy.io/integrations
```
PERCY_GZIP=true
It will fail 3/10 time with error `[percy:core] TypeError: Cannot read properties of undefined (reading 'url')`
Some of the content are already zipped and 
Fixed build https://percy.io/9560f98d/web/pradum-debugging-9d5722f8/builds/38137551
> 🐛 fix for PERCY_GZIP flag

- packages/client/src/client.js
- packages/dom/src/clone-dom.js
- packages/dom/src/serialize-base64.js
- packages/dom/test/serialize-base64.test.js
Changes:
- Now we cache data src resources - is helpful in some cases where we were getting hundreds of repeated resources as those were on different dom nodes
- We now set src on cloned node using `data-percy-serialized-attribute-src` - which is later replaced with src. This allows us to avoid network call that browser makes when we set src on any cloned node.
> Cache base64 resources

- packages/core/src/network.js
- packages/core/test/discovery.test.js
Description: 
1. Snapshot upload is failing for resources with size more than 100mb. 
2. Fix: Checking content-length for the response
3. If content-length > MAX_RESOURCE_SIZE (25MB) we are skipping the resource before processing it. 
JIRA: https://browserstack.atlassian.net/browse/PER-4439
> added check for resources greater than 100mb

- packages/config/src/defaults.js
- packages/config/src/utils/normalize.js
- packages/config/test/index.test.js
Description: 
1. Sanitising keys for config file. 
2. Skipping unsafe keys.
> skipping unsafe key

- packages/core/src/snapshot.js
- packages/core/src/utils.js
- packages/core/test/percy.test.js
Have added a normalization function in validateSnaphotOptions to convert any type of casing of options to camecase making them case-insensitive.
Example: 
If a user provides options as:
```
options = {
nAmE: 'Snapshot 1',
url: 'http://localhost:8000',
WiDtHs: [375, 1280],
sCoPe: '#app',
sCoPeOpTiOnS: { scroll: true },
mInHeIgHt: 1024,
eNaBlEJaVaScRiPt: true,
eNaBlELaYoUt: false,
cLiEnTInFo: 'client-info',
eNvIrOnMeNtInFo: 'env-info',
sYnC: true,
tEsTcAsE: 'testCase',
lAbElS: 'label1',
tHtEsTcAsEeXeCuTiOnId: '12345'
}
```
These will be converted to:
```
options = {
clientInfo: 'client-info',
environmentInfo: 'env-info',
name: 'Snapshot 1',
url: 'http://localhost:8000',
widths: [375, 1280],
scope: '#app',
scopeOptions: { scroll: true },
minHeight: 1024,
enableJavaScript: true,
enableLayout: …
```
> Added normalization function to make options case-insensitive

- packages/cli-upload/test/upload.test.js
- packages/client/src/client.js
- packages/client/test/client.test.js
- packages/config/src/validate.js
- packages/config/test/index.test.js
- packages/core/src/config.js
- packages/core/src/utils.js
- packages/webdriver-utils/src/providers/genericProvider.js
- packages/webdriver-utils/src/providers/playwrightProvider.js
- packages/webdriver-utils/test/providers/genericProvider.test.js
- packages/webdriver-utils/test/providers/playwrightProvider.test.js
added support for regions
```const obj1 = {
elementSelector: {
boundingBox: { x: 100, y: 150, width: 300, height: 200 },
elementXpath: "/html/body/div[1]/div[1]/header/div[2]/nav/ul/li[1]/a",
elementCSS: ".ad-banner"     -> only one of them and mandatory
}
padding: {
top: 10,
left: 20,
right: 15,
bottom: 10
}
algorithm: "intelliignore",  -> mandatory, it can be standard, layout, ignore, intelliignore
configuration: {  for layout, ignore nothing is required
diffSensitivity: 2,  // these all are applicable for standard and intellignore
imageIgnoreThreshold: 0.2,
carouselsEnabled: true
bannersEnabled: true 
adsEnabled: true
},
assertion: {
diffIgnoreThreshold: 0.4,
}
};
percy.snapshot("Homepage", regions:[obj1, obj2, ..]);
```
also added validations
> added support for regions for SDKs

- packages/core/test/discovery.test.js
- packages/dom/src/clone-dom.js
- packages/dom/src/serialize-dom.js
- packages/dom/test/serialize-dom.test.js
Recreating custom element and not cloning them directly as it causes attributeCallback function to get triggered
Issue ->
- When were were doing cloneNode on a custom element. If attributeCallback is defined on that custom element then it was getting triggered, which caused spike in cpu usage.
- We are now recreating the node and not cloning them.
> Recreating custom element and not cloning them directly as it causes attributeCallback function to get triggered

- packages/dom/src/serialize-dom.js
- packages/dom/test/helpers.js
- packages/dom/test/serialize-dom.test.js
Added a check to prevent errors when ctx.clone.body is null, such as in about:blank pages. This ensures that accessing ctx.clone.body?.nextSibling doesn't throw, maintaining stability in edge cases where no <body> exists.
> Adding check for null body in serializeDOM

- packages/core/src/browser.js
- packages/core/src/config.js
- packages/core/src/session.js
- packages/core/test/discovery.test.js
Introduces a `closeBrowser` option in launch settings to control browser closure after tasks.
Updates logic in `Browser` and `Session` classes to respect this option, enabling flexibility in workflows.
Includes relevant unit tests to ensure proper handling of the `closeBrowser` option in various scenarios.
> Adds configurable browser close behavior

- packages/client/package.json
Seeing import { snakecase } from '@Percy/config/utils'; error while running CLI, facing the same issue while trying to run support CLI.
added import dependency
> Snakecase import fix

- packages/core/src/config.js
- packages/core/src/discovery.js
- packages/core/src/page.js
- packages/core/test/percy.test.js
- packages/dom/src/clone-dom.js
- packages/dom/src/prepare-dom.js
- packages/dom/src/serialize-dom.js
- packages/dom/test/serialize-dom.test.js
This pull request introduces a new configuration option, `forceShadowAsLightDOM`, which enables the serialization of shadow DOM content as regular light DOM in Percy snapshots. This feature is integrated throughout the core and DOM serialization logic, with comprehensive test coverage to ensure correct behavior in various scenarios, including nested and custom elements, slot content, and interaction with the existing `disableShadowDOM` flag.
**Configuration and Core Integration:**
* Added the `forceShadowAsLightDOM` boolean option to the `configSchema` and `snapshotSchema` in `packages/core/src/config.js`, allowing users to enable this feature via configuration. [[1]](diffhunk://#diff-e7c1269ddb64f1de14c2c79cac204c16cfc3f8d8535512d218f8e4ad8efc63b6R74-R77) …
> added flag forceShadowAsLightDOM

- packages/dom/src/serialize-cssom.js
- packages/dom/src/serialize-inputs.js
- packages/dom/src/utils.js
- packages/dom/test/serialize-css.test.js
- packages/dom/test/serialize-dom.test.js
- packages/dom/test/utils.test.js
Before:
`styleSheetFromNode()` built its scratch document using `document.cloneNode()`.
This produced a head-less document where appended <style> tags never created a CSSStyleSheet. As a result, the helper often returned null, and later code attempted to access null.cssRules, causing TypeError exceptions on some sites (especially with CSS-in-JS or Safari/Firefox).
After:
`styleSheetFromNode()` now uses `document.implementation.createHTMLDocument()` to create a fully-formed scratch document, appending cloned <style> nodes into its <head>. This reliably initializes CSSOM across browsers. Additional null and SecurityError guards were added around .cssRules access, so unreadable or missing sheets are skipped instead of crashing.
Impact:
- The old `cloneNode()` method worked on some browsers …
> Fix Serializing CSS Stylesheet Issue - A11Y

- karma.config.cjs
- packages/client/src/proxy.js
- packages/sdk-utils/package.json
- packages/sdk-utils/src/proxy.js
- packages/sdk-utils/src/request.js
- packages/sdk-utils/test/proxy.test.js
- packages/sdk-utils/test/request.test.js
- yarn.lock
1. Added support for proxy for PoA session for communication with browserstack hub.
2. The proxy usage changes are similar to proxy present in `@percy/client` package
3. Why it was needed to be implemented separately for sdk-utils - [[here](https://github.com/percy/cli/pull/2000/files#diff-60d1759380643130d5b97b609ceaa4edf89edc6a5308040e68a4fe0c2979a037R15)] 
1. Have setup a local proxy and analysed the logs of proxy
2. With current CLI, only percy.io calls are going via proxy
3. With this change `percy.io` and `hub-cloud.browserstack.com` both goes via proxy
> [PPLT-4565] | Add Proxy support for PoA Session for communication with `hub.browserstack.com`
