packages/core/src/percy.js, packages/core/test/percy.test.js
If the execute function causes page navigation, the snapshot fails to be taken due to `@percy/dom` not being injected on the resulting page. Furthermore, the provided URL was used as the snapshot URL when in reality that URL may change depending on page navigation.
Fixes #98 
Move the script injection to after `execute` is called and do not inject the script if it has already been injected. The resulting document's URL is then used as the snapshot URL.
=> 🐛 Inject @percy/dom after executing page methods

packages/core/src/server.js, packages/core/test/server.test.js
This allows us to use the new CLI with any non-JS SDK _right now_. This is because the only breaking changes for those non-js SDKs was:
- Change in server path for where to get the DOM library
- Change in function signature for how the dom library works
This PR adds back the `percy-agent.js` server endpoint (with a deprecation log), and also adds a wrapper to match the old function signature.
JS SDKs will still need to be updated, since they carry `@percy/agent` as a dependency (and use the SDK util method to require the DOM JS)
=> ✨ Add backwards compatability for DOM library fetching

packages/cli-config/src/commands/config/migrate.js, packages/cli-config/test/migrate.test.js
This key was missed during #138. This PR fixes it.
=> 🐛 Fix config migration for disable-cache

packages/cli-config/src/index.js
I noticed that these exports were broken. This fixes them.
=> 🐛 Fix cli-config exports

packages/logger/src/logger.js
It might become more common to verify the log level before performing some logic. Since log levels are well, levels, it's slightly more complicated than an equal operator. Rather than repeating log level logic, we can expose the `shouldLog` instance method to any logger groups. This will allow them to determine if their specific logging group is allowed to log a specific log level. 
For example, `logger('group:id').shouldLog('info')` will only return truthy if both the log level is either `info` or `debug`, and the group id is present in any `PERCY_DEBUG` environment variable. This is much better and more succinct than checking the log level alone.
=> ✨ Expose logger's shouldLog method

packages/cli-command/README.md, packages/cli-config/README.md, packages/cli-exec/README.md, packages/cli/README.md, packages/client/README.md, packages/client/src/client.js, packages/config/README.md, packages/core/README.md, packages/core/src/config.js, packages/core/src/discovery/browser.js, packages/dom/README.md, packages/logger/README.md, packages/sdk-utils/README.md
In preparation to leave beta status, I went through and made sure all of the readmes were up to date. I also added tables of contents in readmes that didn't have something similar already, and made a couple of small semantic adjustments to variables  in the code.
My keyboard was really acting up during this, so be on the lookout for random characters. 👀
=> 📝 Update documentation

packages/core/src/percy.js
A small fix for a debug log logging the wrong variable.
=> 🔊 Fix debug log logging the wrong variable

packages/core/src/discovery/network.js, packages/core/src/server.js, packages/core/test/asset-discovery.test.js
[Server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) can clog up asset discovery because the request is left open. From my research, it seems like this would only be a problem when JS is enabled. From experience writing the new Storybook SDK, it happens with hot module reloading; which lines up with JS needing to be enabled.
We can handle the [`Network.eventSourceMessageReceived`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-eventSourceMessageReceived) devtool event and remove the open request from being tracked. This prevents asset discovery from hanging on network idle while still waiting for at least one event before considering the network to be idle. This also prevents us from capturing these event streams which might lead …
=> 🐛 Fix asset discovery issue with event streams

packages/client/src/request.js
In other SDK related packages, we occasionally borrow this request util for its retryability. While using it in the new Storybook SDK to wait for the Storybook server to become available, I discovered that sometimes it can be useful to retry 404s when the file will eventually exist (if the server starts before code finishes compiling).
This PR adds a `retryNotFound` option to the request util to enable this behavior since we don't normally want to retry 404s in most situations. Since this option will not be utilized internally by client, no tests were added here. If we add much more options to this that aren't used internally, we may want to add a unit test (or in the future move shared utils to a shared package).
=> ✨ Add additional retry option to client request util

.github/ISSUE_TEMPLATE/bug_report.md
This adds an issue template to the repo to help gather the right info from bug reports
=> 📝  Add bug issue template

.github/release-drafter.yml
Updates the release drafter config to match our new standardized labels
=> 🧹 Update release drafter config

packages/cli-snapshot/README.md, packages/cli-snapshot/src/commands/snapshot.js, packages/cli-upload/README.md
A couple options aren't technically documented in the readmes. We should also update the docs site as well.
=> 📝 Update upload and snapshot readmes

.github/dependabot.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/typecheck.yml, .github/workflows/windows.yml, packages/core/package.json, yarn.lock
Hi! This pr allows dependabot to handle github actions dependencies management.
I also included the update of the current dependencies.
=> ⬆️ Update dependencies on and allow github-actions management by dependabot

packages/core/src/network.js, packages/core/test/discovery.test.js
With network tracking, there are a number of events which need to be handled to manage requests properly. While some of these events are intended to happen in a specific order, and handlers are written in a way to handle an unexpected order of events, there aren't actually guards in place to prevent handling seemingly duplicate events.
The changes in this PR were found in Puppeteer after discovering a font-related issue. We have a history of font-related issues, so I thought to give these changes a try here. The specific issue that prompted these safeguards are a result of this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1196004
Our network handling isn't an exact 1:1 of Puppeteer's, so I wasn't able to reproduce the issue with a test for the same. One likely …
=> ✨ Improve network tracking resilience

.github/workflows/stale.yml
Forgot to add `stale-issue-label` to the config 🤦🏻‍♂️ (all of the repos added a generic "Stale" label 🤢 )
=> 🧹 Fix stale issue label

packages/cli-command/src/command.js, packages/cli-command/test/command.test.js
At some point (soon), we might want to deprecate some flags. This PR draws inspiration from #494 with a similar API to deprecate and map CLI flags.
=> ✨ Allow automatically deprecating and mapping CLI flags

.github/ISSUE_TEMPLATE/bug_report.md
We now have a nice debugging doc for the SDKs, it would be good to link to this in the issue template to hopefully cut down on the common setup issues we see questions about.
=> 📝 Update issue template to include new debugging doc

packages/config/src/load.js, packages/config/test/index.test.js
This wraps and improves the config file searching with a try-catch to handle unexpected not found errors and also returns early during loading when the `bail` option is provided.
=> ✨ Improve bail ability of config loading

packages/core/test/unit/install.test.js
While writing a new test suite for an unrelated feature, I utilized `memfs` and `quibble` to mock the filesystem. For some reason, this caused the install tests to fail (seems one of those libraries doesn't clean up as good as it should). Moving these tests to also use the mock filesystem makes them happy again.
=> ✅ Update install unit tests to use mock filesystem

package.json, scripts/build.js, yarn.lock
This PR makes a few small repo script adjustments
- Fix the watcher import in the build script
- Run repo tests in parallel
- Remove extraneous babel dev dependency
=> 🔨 Repo script fixups

package.json, scripts/chromium-revision.js
This fixes the chrome revision script we use to find the right revisions for the asset discovery browser
=> 🐛 Fix Chrome Revision script

packages/env/src/environment.js, packages/env/test/harness.test.js
This adds support for [Harness](harness.io) by referencing their environment variables so that Percy can pick them up ([#1852](https://browserstack.atlassian.net/browse/PER-1852)).
=> ✨ Add support for Harness CI

packages/cli/README.md
* moved to internal confluence
=> 📝 Remove publish info

.github/workflows/sdk-regression.yml
Follow up from https://github.com/percy/cli/pull/1211
- Add testing for WDIO v2
- Add more SDKs - python, capybara and appium-js
- Fix PR branch name not getting updated on `issue_comment` event
Reference Run - https://github.com/percy/cli/actions/runs/4565663845
=> Regression: WDIO test v2 and add more SDKs

packages/client/src/client.js, packages/client/test/client.test.js, packages/core/src/config.js
Adding support for code based ignore region.
=> ignored element support implementation

.github/workflows/sdk-regression.yml
Follow up on https://github.com/percy/cli/pull/1235
=> SDK Regression fix context conflict

packages/client/test/client.test.js, packages/env/package.json, packages/env/src/environment.js
Changes:
- Added a debug log line, for debugging any kind of env issues
=> 🧹 Add debug logs for env package

packages/webdriver-utils/src/providers/genericProvider.js, packages/webdriver-utils/test/providers/genericProvider.test.js
Adding percyCSS option for PoA.
This will allow to have user controlled stabilisations while taking screenshots.
The property will be applied and once screenshot is taken it will be removed.
=> Adding percyCSS options for PoA [Snapshot level]

packages/dom/src/serialize-cssom.js, packages/dom/test/serialize-css.test.js
Code Changes to capture the Blob CSS assets.
=> [PER-2252] Blob assets not being serialized by Percy

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
Releasing `v1.27.0-beta.0` i.e. Percy on Automate
=> 🔖  v1.27.0-beta.0

packages/core/src/config.js, packages/webdriver-utils/src/providers/genericProvider.js, packages/webdriver-utils/test/providers/genericProvider.test.js
Previous PR: https://github.com/percy/cli/pull/1318
=> Consider region schema fix

packages/webdriver-utils/src/driver.js, packages/webdriver-utils/test/driver.test.js
**Context-**
- Adding anchor comment to grep-on when looking for scripts executed via percy
=> [PPLT-2230] Add anchor comment to executeScript

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
**Description**-
- Bump version to `1.27.0-beta.1`
=> 🔖  feat: bump to 1.27.0-beta.1

packages/client/src/client.js, packages/client/test/client.test.js, packages/core/src/config.js, packages/webdriver-utils/src/providers/automateProvider.js, packages/webdriver-utils/src/providers/genericProvider.js, packages/webdriver-utils/test/providers/automateProvider.test.js, packages/webdriver-utils/test/providers/genericProvider.test.js
Description:
Sending windowHeight to Percy API for calculation of header and footer in android
=> Sending window height for android footer calc

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
Releasing version : `v1.27.0-beta.2`
=> :bookmark: Bumped to v1.27.0-beta.2

packages/core/src/config.js, packages/webdriver-utils/src/index.js
Capturing Screenshot Timings and Metrics.
=> Adding CLI Metrics to measure client duration

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
* ✨ Percy on Automate Support + Increased Device Coverage
* Bump version to `v1.27.0`
Refer to more details here - https://docs.percy.io/docs/integrate-functional-testing-with-visual-testing
=> :bookmark: release v1.27.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> Revert "feat: bump to 1.27.1-beta.0"

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
Releasing Percy Build - `v1.27.2`
=> :bookmark: release v1.27.2

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
Release cli - `v1.27.3-beta.0`
=> :bookmark: release v1.27.3-beta.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> :bookmark: release v1.27.5-alpha.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
:bookmark: release-`v1.27.4-beta.4`
=> :bookmark: release-v1.27.4-beta.4

packages/webdriver-utils/src/providers/automateProvider.js, packages/webdriver-utils/test/providers/automateProvider.test.js
[CLI][SDKs] Implement Warning + Disable Percy for unsupported combinations
Here we are showing Error Message to user if the browser, OS and selenium combination is not a valid one.
=> ✨ Implement Warning + Disable Percy for unsupported combinations

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 release-v1.27.5-beta.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> :bookmark: release-v1.27.5-beta.1

packages/client/test/client.test.js, packages/core/src/config.js, packages/webdriver-utils/src/providers/automateProvider.js, packages/webdriver-utils/test/providers/automateProvider.test.js
Sending the screenshotType whether it is a single page or fullpage to API for future purposes
=> Sending screenshotType to API

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 v1.27.7-beta.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 releasing v1.27.7

packages/cli-exec/test/exec.test.js, packages/cli-exec/test/start.test.js
Added 1 second sleep after start server call.
=> Fix flaky cli exec package tests

packages/core/src/utils.js, packages/core/src/wait-for-job.js, packages/core/test/wait-for-job.test.js
Added timeout for comparison of 90 seconds and 08: 30 min for snapshot
=> Add timeout in sync cli

packages/dom/test/serialize-css.test.js, packages/dom/test/serialize-dom.test.js
Fixing @percy/dom test for deprecation of shadowroot. Instead using shadowrootmode.
=> Fixing test for deprecation of shadowroot. Instead using shadowrootmode

packages/webdriver-utils/src/providers/automateProvider.js, packages/webdriver-utils/test/providers/automateProvider.test.js
Added sync parameter in percyScreenshotEnd call
=> Added instrumentation for sync cli

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
:bookmark: release-v1.28.0
- Releasing CLI out of beta
=> :bookmark: v1.28.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
Bump version to v1.28.1-beta.1
=> v1.28.1-beta.1

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> Releasing v1.28.2-beta.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> Releasing v1.28.2-beta.1

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> releasing latest 1.28.2

packages/dom/src/serialize-base64.js, packages/dom/test/serialize-base64.test.js
JIRA: https://browserstack.atlassian.net/browse/PER-3004
=> serialize base64 in href attribute

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
:bookmark: release - `v1.28.3-beta.0`
=> :bookmark: v1.28.3-beta.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> releasing v1.28.3

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 release-v1.28.4 

.github/workflows/executable.yml
we were getting following error on github action: Unable to find Node version '14' for platform darwin and architecture arm64.
- Have updated architecture.
- Also updated actions/setup-node@v4
Fix is working : https://github.com/percy/cli/actions/runs/8845264119/job/24288814991
=> Fix executable workflow

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 release-v1.28.5 

packages/client/src/proxy.js, packages/client/src/utils.js
log for capturing proxy errors
log for error in uploadResource
=> Added logging for capturing errors

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> Releasing version v1.28.6

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 Release version v1.28.7

.github/workflows/executable.yml, scripts/executable.sh
Added changes for new adding new secrets used for cert rotation. Post this we can directly update secrets and will work.
=> ✨ Changes for new apple cert

packages/core/src/percy.js, packages/core/test/discovery.test.js, scripts/test.js
supporting PERCY_DO_N0T_CAPTURE_RESPONSIVE_ASSETS env variable to disable fetching of responsive assets
=> supporting PERCY_DO_N0T_CAPTURE_RESPONSIVE_ASSETS env variable to disable fetching of responsive assets

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖  Release v1.28.8-beta.1

.github/ISSUE_TEMPLATE/bug_report.md, packages/core/src/api.js, packages/core/test/api.test.js, packages/env/README.md
=> updating docs url

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
Releasing v1.28.8-beta.2 with Playwright in Automate support in beta
=> 🔖 Release v1.28.8-beta.2

packages/webdriver-utils/src/providers/genericProvider.js
Path configuration for driver.js file was wrong wrt to module. It works in local as there we have setup of src.
=> Fixing path for percy on automate file

packages/sdk-utils/src/logger.js, packages/sdk-utils/test/index.test.js, packages/webdriver-utils/src/providers/playwrightProvider.js
Changes:
- Now for all sdks using sdk utils we will automatically capture all error logs
- We can also capture all logs in debug mode
=> ✨ Added log collection to logger of sdk utils

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
- Release beta version v1.28.9-beta.0
=> 🔖 v1.28.9-beta.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> releasing 1.28.9-beta.1

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖  Release v1.28.9

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> Release beta v1.29.0-beta.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> Release stable version v1.29.0

packages/core/src/config.js, packages/core/test/discovery.test.js, packages/core/test/unit/config.test.js, packages/dom/src/serialize-dom.js
Adding `cookies` field in config of domSnapshot
=> Add cookies in config for domSnapshot

packages/client/package.json, packages/client/src/detect-proxy.js, packages/client/src/utils.js, packages/client/test/unit/detect-proxy.test.js, packages/core/src/config.js, packages/core/src/percy.js, packages/core/src/utils.js, packages/core/test/percy.test.js
- Detect system level proxy and log a warning message
- added option useSystemProxy to use proxy which was detected
=> Added logic to auto detect system level proxy

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> Release v1.29.1-beta.0

packages/client/src/proxy.js, packages/client/test/unit/request.test.js
adding request url to proxying request error log
=> adding request url to proxying request error log

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> release-v1.29.1-beta.1

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
releasing stable v1.29.1 version
=> releasing stable v1.29.1 version

packages/cli-exec/test/exec.test.js, packages/cli-exec/test/start.test.js, packages/core/src/percy.js, packages/core/test/percy.test.js
Updated messaging for logs collection
=> Update messaging for collecting logs

packages/config/src/load.js, packages/core/src/percy.js, packages/core/src/snapshot.js
Validate presence of errors in config validator.
Fix: https://github.com/percy/cli/issues/1674
=> Fix of issue id #1674, reporting false positive invalid config warning.

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> release-v1.29.2-beta.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> Releasing v1.29.2

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖  v1.29.3-beta.0

packages/core/src/install.js, packages/core/test/unit/install.test.js
JIRA: https://browserstack.atlassian.net/browse/PER-3637
Add support for PERCY_CHROMIUM_BASE_URL as an Env Var
=> Add PERCY_CHROMIUM_BASE_URL Environment Var

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 Releasing 1.29.3-beta.1

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖  v1.29.3-beta.2

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> release-v1.29.4-beta.1

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖  v1.29.4-beta.2

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 v1.29.4-beta.3

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> releasing v1.29.4-beta.4

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> releasing v1.29.4-beta.5

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 v1.29.4-beta.6

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
releasing stable version 1.29.4
=> releasing stable version 1.29.4

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> Bump Version v1.29.5-beta.0

packages/core/src/percy.js, packages/core/test/percy.test.js
=> 🧹 fix: typo in log

packages/client/src/client.js
Moved error line for verify tile after expected failure
=> Moved error line for verify tile after expected failure

packages/core/src/percy.js
=> fixing warning for labels

packages/env/src/environment.js
Fixing issue -> allowing PERCY_PARALLEL_TOTAL to override CIRCLE_NODE_TOTAL
=> Add override for CircleCI node total

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 v1.30.5-beta.1

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖  Release 1.30.5-beta.2

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-build/src/finalize.js, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/client/src/client.js, packages/client/test/client.test.js, packages/config/package.json, packages/core/package.json, packages/core/src/config.js, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
- Adding Error Capturing on `Finalize` Builds. This was leading to uncaught exception handling for unhandled promise.
=> Adding Error Capturing on Finalize Builds

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 v1.30.6-beta.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json, yarn.lock
=> release v1.30.7-beta.0

yarn.lock
fixing error in releasing beta version
```
lerna WARN If you don't have an npm token, you should exit and run `npm login`
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna ERR! EUNCOMMIT  M yarn.lock
error Command failed with exit code 1.
```
https://github.com/percy/cli/actions/runs/12705661404/job/35417102191
=> fixing error in releasing beta version

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 releasing v1.30.7-beta.1

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 Release 1.30.7-beta.2

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 Release  v1.30.7-beta.3

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
Release beta version 1.30.8-beta.2 
Fixed content length NaN
=> 🔖 Release v-1.30.8-beta.2

packages/dom/src/serialize-cssom.js, packages/dom/test/serialize-css.test.js
Description: 
1. Changed the order in which styles are captured.  
a. If no style links are present then it is prepended.
b. If style links are present the new once's are added in the order in which they are received.
=> fixed style ordering

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 Release v1.30.9-beta.1

packages/client/src/client.js, packages/client/test/client.test.js, packages/env/src/environment.js, packages/env/test/environment.test.js
Description: 
1. Passing unique build uuid from env to create builds.
=> Passing unique build uuid in create build

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 Release v1.30.9-beta.2

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 Release v1.30.9-beta.3

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> releasing 1.30.9-beta.4

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 releasing 1.30.10-beta.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> releasing 1.30.10

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 Release  v1.30.11-beta.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 Releasing 1.30.11-beta.1

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖  v1.30.11

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> releasing v1.31.0

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 v1.31.1-beta.2

packages/core/src/percy.js, packages/core/src/utils.js, packages/core/test/utils.test.js
Ticket - https://browserstack.atlassian.net/browse/PPLT-4314
=> SDK Version Check

.github/workflows/test.yml, lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
Releasing beta version 1.31.2-beta.3
=> 🔖 Releasing v1.31.2-beta.3

packages/webdriver-utils/src/providers/playwrightProvider.js, packages/webdriver-utils/test/providers/playwrightProvider.test.js
Changes - 
1. Updated `mobileOS` to include IOS also for playwright Tests
=> ✨ PoA Support for Playwright with IOS Devices

lerna.json, packages/cli-app/package.json, packages/cli-build/package.json, packages/cli-command/package.json, packages/cli-config/package.json, packages/cli-exec/package.json, packages/cli-snapshot/package.json, packages/cli-upload/package.json, packages/cli/package.json, packages/client/package.json, packages/config/package.json, packages/core/package.json, packages/dom/package.json, packages/env/package.json, packages/logger/package.json, packages/monitoring/package.json, packages/sdk-utils/package.json, packages/webdriver-utils/package.json
=> 🔖 Release v1.31.3-beta.4
